# Analysis and response

This Science Response uses a closed-loop simulation approach to evaluate the 
relative performance of candidate MPs for the BC Sablefish fishery,
using identical methodology to that presented in the previous
MSE cycle [@cox2019evaluating]. The following sub-sections provide 
brief descriptions of the updated data used to condition the 
Sablefish OM, the changes required to fit that data, and 
the new MP elements that were tested. Additional 
details of the simulation procedures, diagnostic checks, and 
performance measure calculations are given in @cox2019evaluating.


In this Science Response we specifically:

1.    Describe OM fits and inferences after fitting 
(conditioning) to updated biomass indices, catch-at-age, and new 
catch-at-age data derived from length-composition sampling of 
Sablefish in the trawl fishery; 
2.    Derive a grid of five reference OMs and five 
robustness trial OMs based on uncertainties about 
Sablefish stock status and productivity (reference OMs) and 
year 2015 recruitment (robustness OMs); and
3.    Simulate and rank candidate MPs under the reference and
robustness OMs based on performance against Fishery Objectives
(see below).


## Methods

### Updates to the OM

Data updated to 2018 included biomass indices and catch-at-age 
for the stratifed random trap survey (StRS), catch-at-age for 
the commercial longline trap fishery, catch and total at-sea 
releases (in biomass units) for the commercial longline trap, 
longline hook, and trawl fisheries. We also obtained new 
catch-at-age and catch-at-length datasets for the trawl fishery 
to help estimate trawl selectivity, which is the key 
determinant of sub-legal Sablefish catch in trawl fisheries. 
The full trawl catch-at-age dataset (with some missing years) 
was derived from an age-length key given age and length data 
from 1972 to 2017.

A number of small changes were made to the OM as 
part of routine attempts to improve fits to various data. These 
included (i) changing the functional form of trawl selectivity 
to a gamma density function (Figure A5), (ii) reducing the youngest modelled 
age class from age-3 to age-2 for all age composition series 
to better reflect the range of age-composition observations, 
(iii) adding new commercial trawl age-composition data (Appendix 
A), (iv) adding an estimated recruitment deviation in 
2015, rather than using the expected recruitment off the 
stock-recruit curve, (v) updating the ageing-error matrix to use 
a simpler normal approximation recommended in the previous CSAS
review [@cox2019evaluating]; and (vi) imposing a standard deviation 
of $\sigma = 0.1$ (on the log-scale) on trawl at-sea release 
observation errors to force a better fit to those data. Previous 
models avoided estimating recruitment in the three most recent years,
mainly because this would have been the first age-at-entry 
observations provided to the model and there is typically little 
information to support those estimates because fish are too small to 
be selected by the fisheries or surveys. However, for this update, 
we made change (iv) above (i.e., estimated recruitment deviation in 2015) 
because we needed to improve fits to recent (very 
high) trawl at-sea release observations. Otherwise, we would be 
simulating effects of at-sea releases based on a model that could not 
adequately fit historical at-sea releases. This change has a 
potentially large impact on simulated MP performance and, therefore, 
is a focus of the robustness OMs (described below).


### Operating model scenarios

#### Reference OMs

The reference OMs were derived using the same method as the previous 
MSE cycle [@cox2019evaluating]. Briefly, we derived five OMs defined by the 
joint posterior distribution of 2018 spawning stock biomass (to reflect 
short-term biological risk) and stock-recruitment steepness (to reflect 
long-term stock productivity risk). The five combinations were chosen to 
represent the joint marginal mean of 2018 biomass and steepness and four 
outer points lying at the intersection of the mean of one variable, 
and the 10th and 90th percentiles of the marginal density of the other 
variable (Figure 1). This set of five OMs was chosen to maintain 
consistency with the previous MSE cycle [@cox2019evaluating]. For each 
of the five posterior points, the operating model was conditioned on a 
sample of 100 posterior draws constrained to lie within a Mahalanobis 
distance of 0.75 units from that point. We then used an empirical 
estimate of the posterior density at each of the five centres as a 
plausibility score for weighting MP performance across the 
five OMs within each of the reference and robustness sets.

#### Robustness OMs

The robustness OMs were identical to the five reference OMs with the exception 
of how the recruitment from the 2015 year class was treated in the OM 
historical conditioning and projections. The reference OM used draws 
from the joint posterior distribution (as defined above) for the 2015 
year class, which is approximately 22 million fish or about 8 times 
the historical average. For the robustness OMs, we simulated recruitment 
based on the stock-recruitment relationship resulting in an
expected 2015 year class that was more similar 
to the long-term average ($\sim 2.63$ million). 

### Fishery Objectives

Objectives for the B.C. Sablefish fishery have been developed 
iteratively over the past decade via consultations between 
fishery managers, scientists, and industry stakeholders 
[@cox2009evaluation; @cox2011management; @dfo2014performanc; 
@cox2019evaluating]. The five primary objectives 
guiding this fishery are:

1.  **P(fSSB > LRP)**: Maintain female spawning stock biomass (fSSB) 
      above the limit reference point $LRP = 0.4B_{MSY}$, where 
      $B_{MSY}$ is the OM female spawning biomass at maximum 
      sustainable yield ($MSY$), in 95% of years measured over two 
      Sablefish generations (36 years);
2.  **P(decline)**: When female spawning stock biomass is between 
      $0.4B_{MSY}$ and $0.8B_{MSY}$, limit the probability of decline over 
      the next 10 years from very low (5%) at $0.4B_{MSY}$ to 
      moderate (50%) at $0.8B_{MSY}$.  At intermediate stock status 
      levels, define the tolerance for decline by linearly 
      interpolating between these probabilities;
3.  **P(fSSB > $B_{MSY}$)**: Maintain the female spawning biomass above 
      a target level of (a) $B_{MSY}$ when inside the healthy zone, 
      or (b) $0.8B_{MSY}$ when rebuilding from the Cautious zone, 
      in the year 2052 with a probability of 50%;
4.  **P(TAC < 1,992 t)**: Minimize probability that annual TAC levels 
      are below 1,992 tonnes measured over two Sablefish 
      generations; and
5.  **MaxCatch**: Maximize the average annual catch over 10 years 
      subject to Objectives 1-4.

Performance measures corresponding to Fishery Objectives 1-4 (in bold) are read as 
"Probability of (condition)". Performance measures are calculated for each 
simulation replicate, and the expected performance for a management procedure 
is summarized by the mean (or median) over the 100 replicates of each simulation. 
Full details of performance measures and calculations are given in 
@cox2019evaluating.

As noted above, there is a price premium for larger size classes of Sablefish, 
which means that the same tonnage of landed catch may yield widely different 
dockside values if the underlying size distributions of individual fish are 
substantially different. This may have consequences for sub-legal management measures
that require landing small Sablefish (e.g., no size limit). Therefore,
in addition to presenting catch performance statistics (e.g., Fishery Objective 5), we 
also computed cumulative revenue over 10 years and average revenue 
per tonne by fleet (because the size composition of the catch also differs by 
fleet).


### Management procedures

A management procedure represents a specific, repeatable algorithm for 
computing annual total allowable catches (TACs) in a fishery. In most cases, 
MPs involve monitoring data, assessment methods for processing data and 
estimating stock status, harvest control rules for translating assessment 
outputs into catch limits, and meta rules that may include constraints on 
TAC changes, as well as conditions (e.g., exceptional circumstances) for 
triggering deviations from the standard MP harvest advice.

The MP currently used to set annual Sablefish TACs was initially developed 
in 2011 and revised in two subsequent MSE iterations. Generally, the 
MP consists of (i) __data__ - landed catch and three biomass indices; 
(ii) __assessment method__ -  a surplus production model with 
observation and process errors for estimating stock biomass from the biomass 
indices and landings; (iii) __harvest control rule__ - a 60:40 harvest control rule 
(HCR) in which the target harvest rate is adjusted from 0% when the estimated biomass 
is below 40% of $B_{MSY}$ to a maximum value when estimated biomass is 
above 60% of estimated $B_{MSY}$; (iv) __a meta rule__ stating that TAC increases are 
0 unless the HCR recommended increase is more than 200 tonnes (TAC decreases 
are always adopted); and (v) __a meta rule__ adjusting the maximum target 
fishing mortality rate from 9.5% in 2017 to 5.5% in 2021.

For this Science Response, we evaluated performance of the current MP for 
Sablefish, a no fishing reference case, and 15 variations of the current MP 
that only vary in their at-sea release management measures. The MP variants are 
constructed by combining three features: 

1. __at-sea sub-legal release cap__ in which all at-sea releases below the cap 
      may be released without penalty and amounts exceeding the cap go to 
      overages. Caps are noCap, 0%, 50%, 100%, and 150% over the average 
      464 t of at-sea releases that occurred between 2006 and 2018. The 
      current MP involves no cap (unlimited at-sea releases without penalty), 
      while a no size limit (**NSL**) case allows no at-sea 
      releases (all fish brought on-board vessels must be landed and 
      counted against the TAC). 
2. __fixed allocation among fleets__ (i.e. trap, longline hook, trawl) of 
      the total at-sea release cap. Allocations are computed based 
      on either recent (rct = $(23\%, 18\%, 59\%)$, 2016 - 2018) 
      or historical (hst = $(30\%, 37\%, 33\%)$, 2006-2018) 
      fleet-specific average proportions of the total annual 
      at-sea releases.
3. __amortization period__ of either 5 (am5) or 10 (am10) years over which to 
      spread at-sea release overages to future TACs. 


In this Science Response, MPs are named by combining the three at-sea
management measures detailed above: CAP_ALLOCATION_AMORTIZATION. For example, 
the **cap.5_hstAl_am5** MP involves a total at-sea 
release cap that is 50% (0.5) of the historical average (**cap.5**), a cap 
allocation among fleets that is based on the historic (2006-2018), 
fleet-specific average proportions (**hstAl**), and a 5-year amortization 
period for at-sea release overages (**am5**). The two special cases to this
naming convention are the current MP (**noCap**), which has no cap, 
and no size limit MP (**NSL**), which has no releases (all fish are landed, 
regardless of size). For 0% caps, only the amortization period for overages 
would apply (e.g. **cap0_am5**) with all at-sea releases counted as overages.

#### A worked example at-sea release management measures for **cap.5_hstAl_am5**.

To illustrate how we simulated the implementation of the at-sea release
management measures, below we provide the sequence of calculations used to establish 
annual at-sea release caps and then how they affect future TAC allocations. 
In the computations below, $t$ is year, $g$ is fleet, and $p(g)$ is proportion 
of releases allocated to fleet $g$.

1.    Calculate 50% at-sea release CAP for year and fleet (464 t is the
      2006 - 2018 average):
\begin{equation*}
            CAP(t,g) = 0.5 \cdot 0.464 \cdot p(g).
\end{equation*}
2.    Run simulation for year t to get actual at-sea releases: $R(t,g)$.
3.    Calculate overage $o(t,g)$ for the year as the difference between 
      actual releases $R(t,g)$ and the $CAP(t,g)$:  \tabularnewline
\begin{equation*}
            o(t,g) = R(t,g) - CAP(t,g).
\end{equation*}
4.    Amortization period is 5 years, so add 1/5th of this year's overage.
      to the accumulated overage account $O(t+k,g)$ in each of the next 5 years: 
\begin{equation*}
            O(t + k,g) = O(t+k,g) + o(t,g)/5, \mbox{ for } k = 1, ..., 5.
\end{equation*}
5.    Get adjusted legal-sized Sablefish TAC for next year by subtracting 
      overage account for that year from initial $TAC'$ ($TAC'$ set by the MP 
      prior to at-sea management measures): 
\begin{equation*}
            TAC(t,g) = TAC'(t,g) - O(t,g).
\end{equation*}


This approach aims to create an incentive to avoid sub-legal Sablefish via 
future TAC reductions (assuming one-for-one accounting of sub-legal biomass 
to legal sized Sablefish biomass), while also allowing some flexibility 
year-to-year for unpredictably large at-sea releases in any given year. Note 
that the overage account can never be less than zero, so that TACs cannot be 
increased above the initial TAC set by the first stage MP (i.e., banking of 
TAC cannot occur).

### Management procedure tuning

The Sablefish management strategy evaluation quantifies MP performance 
against performance statistics representing each of the the Fishery 
Objectives. The first three performance statistics are represented by biomass 
conservation performance against the LRP, short-term probability of decline, 
and achieving a long-term target at or near $B_{MSY}$, while the fourth and 
fifth ones relate to maintaining catch levels above an industry-preferred 
floor and short-term average catch. It is rare that two MPs would have comparable 
performance across four of these performance statistics while only differing on one. If 
this were the case, then the decision on which MP is preferred would be 
straightforward – choose the MP with better performance on the fifth statistic. 
Unfortunately, MPs typically differ on all five performance statistics simultaneously, which 
makes it difficult to compare performance without, at least, establishing some 
equivalency between conservation probabilities (Fishery Objectives 1-3) and 
short-term average catch (Fishery Objectives 5). 

Management procedure tuning provides a means of establishing equivalent MP 
performance against objectives for which the values and probabilities are 
well established.  For example, maintaining the Sablefish stock above the 
LRP ($0.4B_{MSY}$) with high probability has not been openly debated since 
it is an overarching Canadian policy directive in the Sablefish fishery 
context (at least not debated over the 10+ year history of the Sablefish 
MSE). Similarly, maintaining a low probability of short-term decline has 
also not been debated, probably because avoiding further decline has been 
the key overriding objective of the Sablefish fishing industry since the 
inception of the MSE process. Fishery Objective 3 – spawning biomass in the healthy 
zone within 2 generations – has been debated over the years for practical 
reasons. Specifically, there is concern that achieving Fishery Objective 3 would 
require severe short-term catch restrictions for highly uncertain long-term 
benefits. Over the past year, the Sablefish industry and DFO agreed to revise 
Fishery Objective 3 to achieve biomass in the healthy 
zone by a specific end-year (2052) with at least 50% probability, i.e., 
median fSSB at, or above, $B_{MSY}$. As we demonstrate below, this objective 
is now feasible given Sablefish dynamics and also achievable for a range of 
realistic MPs. However, this raises a new question: how much is it worth 
(i.e., in catch) to improve Fishery Objective 3 performance from, say, 
$P(B_{2052} \geq B_{MSY}) = 0.5$ to $P(B_{2052} \geq B_{MSY}) = 0.55$? The probability 
difference of only five percentage points could mean a difference of several 
hundred tonnes in average annual catch, which would cumulatively add up 
to tens of millions of dollars in revenue. MPs that perform better 
under Fishery Objective 3 almost always do so at the expense of performance
under Fishery Objectives 4 and 5. 

We aimed to simplify interpretation of MP performance by tuning all MPs to 
a standard $P(B_{2052} \geq B_{MSY}) = 0.5$, which ensured that all MPs meet 
Fishery Objectives 1-3.Tuning was achieved by iteratively adjusting $F_{2021}$, 
which is the maximum target fishing mortality rate scheduled for 
Year 2021 (as part of 5-year phase-in period for the current MP)
[@cox2019evaluating], until each MP satisfied Objective 3, i.e., 
$P(B_{2052} \geq B_{MSY}) = 0.5$. These $F_{2021}$ target maximum 
harvest rates then replace the scheduled maximum target harvest rate 
of 5.5% for Year 2022 and beyond.

Each MP was tuned seperately to the reference and robustness OM scenarios, 
leading to different $F_{2021}$ values for each MP (i.e., once for each 
OM). We then simulated a cross-test in which $F_{2021}$ values tuned 
under the reference OM were applied in MPs for the robustness OM and 
vice versa. The cross-test reveals the potential biological and catch 
consequences of using the wrong $F_{2021}$ values.

## Results

### Operating model update and implications for stocks status

Operating model fits to survey and fishery biomass indices were similar to 
previous versions, where both the model and data showed a long-term steady 
decline. The most recent two stratified random survey (StRS) data points 
(2017 and 2018) were substantially higher than the preceding 15 years, 
suggesting potential increases in the offshore stock biomass (Figure 2). 

In general, the age-structured OM fit the age-composition data 
reasonably well (Figure 3). Fits to the trap fishery age-composition 
continued to show a large positive residual at the plus-group age 35+ for males, and to a more neglibale extent for females (Figure 3, Trap:). Fits to the trawl age-composition also also showed a large 
positive residual for age-2 males, which appeared to arise from the 2017 and 
2018 samples that were large and, therefore, tended to drive the average to have 
what appeared to be a large positive residual at age-2. This was 
a potential contributing factor to the estimated size the estimated 2015 year-class.

Model fits to the standardized survey were similar to previous OM versions — 
patterns lie somewhere between the fishery age-composition fits (worst) 
and StRS fits (best) (Figures 2 and 3). The OM continued to fit StRS very well, 
which probably arose because the StRS is specifically designed for 
monitoring the offshore Sablefish population (unlike all other data
series).

The updated stock status of Canadian Sablefish depended on the absolute size 
of the 2015 year-class (age-3 in assessment Year 2018). The raw 
estimate of this year-class was about eight times the historical average (see 
Robustness OMs section above; Figure 4, bottom row), which created the 
impression of the largest recorded recruitment from one of the 
lowest spawning biomasses ever observed. Such a high recruitment at low 
spawning biomass had cascading effects on the model parameter estimates, 
biological reference points, and estimated current biomass. These effects 
included: (i) the estimated stock productivity (i.e., stock-recruitment 
steepness parameter) was adjusted upwards; (ii) the most productive stock 
size ($B_{MSY}$) was adjusted downwards, because the stock is apparently more 
productive at low biomass; (iii) the optimal fishing mortality rate 
($F_{MSY}$) was adjusted upwards because the more productive stock can 
sustain higher fishing pressure; and (iv) current spawning biomass was 
adjusted upwards because about 20-25% of age-3 fish were maturing. Although 
these were positive and encouraging signs that Sablefish status is improving, 
there was some risk in tuning future MPs to substantial 
model changes that arose from a small number of observations. Other 
Pacific groundfish fisheries (e.g., Pacific Hake [*Merluccius productus*]
and Gulf of Alaska Sablefish) have treated initial large estimated 
recruitments with caution until the data used to estimate them
more fully materialize. Here, we dealt with the uncertainty in 2015 
year-class size by developing reference (using age-3 data) and 
robustness (ignoring age-3 data) OMs for use in evaluating 
MPs.

Under the large 2015 year class, the OM fit showed
the Sablefish stock status as generally good (Table 1, 2018 Fit). 
Spawning biomass in 2018 was about twice the limit reference point 
(LRP), up from about 1.5 times the LRP, which
was itself revised from the 2016 fit of about 1.17 times the LRP . This
change indicated that the BC Sablefish stock might have moved
out of an overfished state. Similarly, the posterior probability 
of the last year's biomass being above the limit 
reference also improved from 2016 to 2018, increasing 
from 93% (2016 fit) to 100% (2018 fit).

### Management procedure evaluation results

#### Reference OM set under reference $F_{2021}$ tuning

As expected, recruitment from the 2015 year class was the primary driver
of projected spawning biomass and fishery outcomes in the reference 
OM simulations. Spawning biomass increased rapidly over the first 
five years of the projection period as age-3 (i.e., 2015
year class) fish became fully recruited to the fisheries and then the 
spawning biomass (Figures 4 and 5, top row). Spawning biomass then trended 
downward toward $B_{MSY}$ over the long-term as the 2015 year class was fished down
and recruitments returned to expected values around the stock-recruitment
relationship (i.e., recruitments for 2016 onward are all simulated off the
stock-recruitment relationship). 

Under these conditions, all MPs met all the biological criteria 
defined by Fishery Objectives 1-3 (Table 2). All tuned MPs were able to meet Fishery
Objective 3, where median spawning biomass (top row of Figure 5) achieves 
$B_{MSY}$ (horizontal dashed line with green dots at end points) by the
final year (2052). Some MPs are able to achieve $B_{MSY}$ 15-20 years prior to 
the final year, while others just make $B_{MSY}$ by the final year.

Tuning MPs to meet Fishery Objectives 1-3, and specifically
treating Fishery Objective 3 as a target, focuses MP performance
differences on average annual catch over the next 10 years (Table 2; Fishery Objective
5). As expected, MPs with more restricted at-sea release 
management measures ranked higher in terms of 10-year average catch (Table 2) 
with the values ranging from 4,530 t per year for no size limit (MP17 **NSL**) 
to 3,710 t per year for management measures with a cap 150% higher than average, 
recent cap allocation among fleets (i.e., allocating 59% to trawl), and 5-year 
amortization (MP14 **cap1.5_rctAl_am5**). This difference was attributable 
to two factors. First, the key assumption here was that fishing activity 
stops once the TAC is reached, so no size limit results in less mortality 
of sub-legal fish over all fleets. This led to a large reduction in 
growth overfishing for the no size limit MP — gains in Sablefish 
body growth were much higher than losses due to natural mortality in 
sub-legal size classes — and, therefore, average weight of legal-sized 
fish in the catch is larger. Second, the fishery could operate at higher 
fishing mortality rates because survival over sub-legal size classes 
was higher and therefore more fish recruit to fisheries and the 
spawning stock. Indeed, the apparently conservative current MP 
maximum target $F=5.5\%$/yr was largely the result of lower survival 
through sub-legal size classes, which inhibited MPs from meeting 
the future spawning biomass Fishery Objective 3. In contrast, the no 
size limit MP almost met Fishery Objective 3 despite a maximum target 
$F=7.5\%$/yr on legal-sized fish (Table 2; $F_{2021}$).

Differences in average annual catch were smaller among at-sea management measures 
that involved a size limit. A 0% at sea-release cap and five year
amortization (MP6) resulted in catches about 400 t higher than the 
current MP (MP15; Table 2), while the gain was 300 t for a 10-year 
amortization (MP5).  

An at-sea release cap of 50% of the historical average resulted in average 
annual catch levels 160 t and 300 t higher than the current MP, depending on the allocation
and the amortization period (MP3 and MP4 vs. MP15; Table 2). Interestingly,
a 10-year amortization with a 0% cap gives identical 10-year average catch
to a 50% cap with a historical allocation and 5-year amortization period 
(MP5 vs MP6; Table 2).

An at-sea release cap equal to 100% of the historical average also produced 
200 t more average annual catch than the current MP, as long as the 
cap was allocated according to the historical at-sea release proportions 
and amortized over five years (MP8 vs MP15, Table 2). The similarity to the 
lower 50% caps described above mainly reflects cap allocation to the trawl 
fleet, where the recent allocation (59%) is approximately twice the historical 
(33%), so switching to the lower, historical allocation allowed for doubling 
the cap, i.e., the total at-sea release amounts allocated to the trawl fleet 
were similar. In general, the historical allocation options ranked higher 
than the recent allocations because the historical allocation involves 
lower at-sea releases by the trawl fleet. The amortization period did not have as 
noticeable an effect as the overall cap and allocation options, in that 
order.

Increasing the cap to 150% of the historical average produced the lowest 
average annual catch, despite the current MP having no cap at all 
(MP13 vs 15; Table 2). Although average 10-year catches were similar, 
at-sea releases in the current MP (**noCap**) change mainly with 
recruitment and therefore have less impact than a 150% cap, which decoupled 
at-sea releases and recruitment to some (small) degree and allowed trawl 
fishing to continue past current sub-legal catch rates.

As caps increased under recent at-sea release allocation,
the effect of amortization switched from 5 years being better (under low 
caps) to 10 years being better (under high caps). Although the differences 
were small (MP12  vs MP3; Table 2), the switch 
probably occured because there is little to no growth overfishing benefit 
of amortization at high caps and recent allocations, which would mean 
higher trawl releases than present. In this case, the amortization period 
had a direct effect on TACs, with longer amortization periods having less 
impact because overages spread over the longer period have less 
impact on annual TAC adjustments.

We initially expected that a no size limit and/or lower cap management measures 
would negatively affect fishery revenue because the landed catch 
would consist of higher proportions of sub-legal fish. Price premiums 
for Sablefish (Table 3; C. Acheson per comm., Spring 2019) may result 
in several dollars per pound difference between sub-legal (< 3 lbs) and 
large (4/5+) legal-sized Sablefish. 

Indeed, the average revenue per 
tonne was approximately $170 lower for a no size limit trap fishery 
compared to noCAP (Table 4), while revenue was approximately $20 
and $1,070 per tonne lower for longline hook and trawl landings, respectively. 
Size-selectivity for trap, and especially longline hook, fisheries is 
shifted far enough toward larger sizes that the impacts of retaining 
smaller fish are relatively small compared to the benefits of higher 
average TACs. Cumulative revenues over ten years were 
$47 million, $18 million, and $15 million higher for trap, longline 
hook, and trawl fisheries under the no size limit MP compared to 
the next best MP from an average annual catch perspective (i.e., MP6, 
**cap0_am5**; Table 4).

The next best at-sea release management measures, from a total catch and
cumulative revenue perspective, after the no size limit MP
were different between trap and longline hook fisheries and trawl. 
For instance, as noted above, MP6 (**cap0_am5**) was the next best 
option for trap and longline hook, in terms of both average annual 
TAC and cumulative revenue (Table 4). In contrast, the next best option
for trawl revenue was MP14 (**cap1.5_rctAl_am5**), which had the 
lowest average annual TAC. The revenue difference for trawl between 
this option and no size limit was only $5 million over 10 years, 
while the revenue differences between MP6 and MP17 for trap and longline 
hook were $33 million and $32 million, respectively. Thus, the results 
suggest trap and longline hook fisheries would benefit from more 
restrictive at-sea management measures while trawl would benefit from the 
least restrictive at-sea management measures other than the status quo, even 
without considering the implications for trawl’s main target fisheries.


#### Robustness OM set under robustness $F_{2021}$ tuning

Unlike the reference OMs, in which biomass and catch increases were large over 
the next decade, Sablefish biomass and catch projections under the robustness 
OMs increased more gradually, and generally required lower fishing rates 
to meet Fishery Objecitives 1-3 (Figures 6 and 7). In fact, these simulations closely 
resemble previous Sablefish MSE results, which suggested that relatively 
conservative harvest strategies are needed over the long-term to meet
the Fishery Objecitives 1-3 [@cox2019evaluating].

Tuning MPs to meet Fishery Objective 3 under the robustness OMs was more challenging 
because higher $F$s had more noticeable impacts on the short-term decline 
objective (P(decline); Table 5). MP tuning produced relatively low target 
fishing mortality rates ranging from 5.2% (current MP) to 7.2% (cap0). 
These low $F$s also had the effect of a higher probability of catches
less than the 1,992 t (Fishery Objective 4); whereas these were 
negligible (< 3%) in the reference OMs, they were all greater than 
15% in the robustness OMs except under the no size limit MP, 
which was 8% (Table 5).

Average annual catch under the robustness OMs ranged from 2,305 t under the 
current MP (MP15, noCap) to 2,767 t under no size limit (MP17, NSL). Thus, 
the current MP with no limit on at-sea releases performed worse than any 
of the cap options by as much as 200 t per year for the top-ranking
cap options (Table 5). There was a slight difference in 
the rank order of MPs (ranked by average 10-year catch) under the 
robustness OMs compared to the reference OMs, although the absolute 
difference among most MPs was small.

Average annual variation in catch (AAV) was 9-11% under the robustness
OMs compared to 7-8% under the reference OMs (Table 5). This probably 
occurs because the stock remains below $B_{MSY}$ for most of the
projection period and is, therefore, assessed below $B_{MSY}$ at times.
Assessment changes in both stock status and the maximum target fishing 
mortality have been relatively common in realized applications of 
Sablefish MPs over the past several years and this causes higher 
interannual variability in TACs.

Cumulative 10-year revenue under the robustness OMs was approximately 
60% of revenue in the reference OMs (Table 6). Although the absolute scales 
differ, the cumulative value patterns were similar to the reference 
set; that is, no size limit produced the highest overall value, as 
well as value in each fleet, and the next best at-sea release management measure 
option, from a cumulative revenue perspective, was the most restrictive 
for trawl and next-most-restrictive for trap and longline hook (MP6, 
**cap0_am5**; Table 6).


#### Cross tests of OMs under opposite $F_{2021}$ tuning

As expected, there was considerable asymmetry of risk between 
MPs tuned under the robustness OMs and reference OMs. For example, 
when MPs were tuned to meet Fishery Objecitives 1-3 under the 
reference OMs, but the 2015 year class 
failed to materialise as in the robustness OMs, almost all MPs failed to meet
the performance criteria for Fishery Objectives 2 and 3 (Table 7). The benefit
of accepting this conservation risk was approximately 150 t of 
extra annual catch, or at most a 6% increase in average annual
catch.

On the other hand, if MPs were tuned to meet Fishery Objecitives 1-3 under
the robustness OMs, but the 2015 year class materialised as expected
under the reference OMs, then, all MPs continued to meet 
the Fishery Objecitives 1 - 3 (Table 8). This more risk averse 
strategy (from a biological perspective) comes with the cost of 
reduced average annual catch of approximately 300 t for all MPs, 
or 6.5-8% of the reference-tuned catch.

