\newpage
\setcounter{table}{0}
# Tables

\newpage

```{r, echo = FALSE}

source(here::here("mseRtools.r"))

recDevYrs <- 10:52
recDevPad <- rep(0,recDevYrs[1]-1)

# read in mcmc output
mcmc    <- as.mcmc(read.table ("./data/mcoutMSY.dat", header = TRUE) )
mcmcDF  <- as.data.frame(mcmc)

# What two variables will we use, and what percentiles?
var1 <- "h"
var2 <- "spawnB54"
form <- paste(var2,"~",var1,sep = "")

var2Mat <- as.matrix(mcmc[,c(var1,var2)])


v1v2    <- lm ( as.formula(form), data = mcmcDF)
mean2d <- apply(X = var2Mat, FUN = mean, MARGIN = 2)
v1v2cov <- cov(var2Mat)

probs   <- c(0.1,0.9)
var1quants  <- quantile (mcmc[,var1], probs = probs)
v1m         <- mean (mcmc[,var1])
v2m         <- coef(v1v2)[1] + v1m*coef(v1v2)[2]

var2quants  <-  quantile(mcmc[,var2], probs=probs)

var2meanline  <-  coef(v1v2)[1] + var1quants*coef(v1v2)[2]

pairs <- list (   loB=c(v1m,var2quants[1]),
                  mhmB=c(v1m,v2m),
                  hiB=c(v1m,var2quants[2]),
                  loh=c(var1quants[1],var2meanline[1]),
                  hih=c(var1quants[2],var2meanline[2]))

pairsMat <- matrix(unlist(pairs),ncol = 2, byrow = TRUE)

densPairs <- lapply (  FUN = dmvnorm, X = pairs, mean = c(v1m,v2m),
                      sigma=v1v2cov)

densPairs <- as.numeric(densPairs)
densPairs <- signif(densPairs/sum(densPairs),3)
names(densPairs) <- names(pairs)

postPairsDF <- data.frame(  OM = names(pairs), 
                            Steepness= signif(pairsMat[,1],3),
                            B2018 = signif(pairsMat[,2],3),
                            density = densPairs )

rownames(postPairsDF) <- NULL

# Take mcmcDF, and turn into a table of posterior
# median estimates for
# B0, R0, M_f, M_m, h, B2019, Bmsy, Fmsy, MSY, B/Bmsy, B/B0

# calculate probability of being above LRP in 2018
# and 2016

mcmcProbLRP2018 <- mcmcDF %>%
                    mutate(OM = "2018 Fit") %>%
                    dplyr::select( OM,
                                    B2018 = spawnB54,
                                    B2016 = spawnB52,
                                    Bmsy ) %>%
                    mutate( B2018gtLRP = ifelse( B2018 >= .4*Bmsy, 1, 0 ),
                            B2016gtLRP = ifelse( B2016 >= .4*Bmsy, 1, 0 ) ) %>%
                    group_by( OM ) %>%
                    summarise( ProbB2016GtLRP = as.character(round(mean(B2016gtLRP),2)),
                               ProbB2018GtLRP = as.character(round(mean(B2018gtLRP),2)) ) %>%
                    dplyr::select(  ProbB2016GtLRP,
                                    ProbB2018GtLRP )


mcmcPostMean <- mcmcDF %>%
                mutate(OM = "2018 Fit") %>%
                dplyr::select(  OM,
                                B0 = "SSB0",
                                M_m, 
                                M_f, 
                                h,
                                B2016 = spawnB52,
                                B2018 = spawnB54,
                                Bmsy, Umsy, legUmsy, MSY ) %>%
                mutate( D2016     = B2016/B0,
                        Dmsy2016  = B2016/Bmsy,
                        Dlrp2016  = B2016/(.4*Bmsy),
                        D2018     = B2018/B0,
                        Dmsy2018  = B2018/Bmsy,
                        Dlrp2018  = B2018/(.4*Bmsy) ) %>%
                group_by(OM) %>%
                summarise_if( is.numeric, summPostMeanSD, se = TRUE ) %>%
                cbind( mcmcProbLRP2018 )
                

# read in mcmc output
mcmc2016    <- as.mcmc(read.table ("./data/mcoutMSY_2016.dat", header = TRUE) )

mcmcProbLRP2016 <- as.data.frame(mcmc2016) %>%
                    mutate(OM = "2016 Fit") %>%
                    dplyr::select( OM,
                                    B2016 = spawnB52,
                                    Bmsy ) %>%
                    mutate( B2016gtLRP = ifelse( B2016 >= .4*Bmsy, 1, 0 ) ) %>%
                    group_by( OM ) %>%
                    summarise( ProbB2016GtLRP = as.character(round(mean(B2016gtLRP),2)) ) %>%
                    mutate( ProbB2018GtLRP = NA ) %>%
                    dplyr::select(  ProbB2016GtLRP,
                                    ProbB2018GtLRP)


mcmc2016    <- as.data.frame(mcmc2016) %>%
                dplyr::select(  B0 = "SSB0",
                                M_m, 
                                M_f, 
                                h,
                                B2016 = spawnB52,
                                Bmsy, Umsy, legUmsy, MSY ) %>%
                mutate( Dmsy2016 = B2016/Bmsy,
                        Dlrp2016 = B2016/(.4*Bmsy),
                        D2016 = B2016/B0 ) %>%
                summarise_if( is.numeric, summPostMeanSD, se = TRUE ) %>%
                mutate( B2018 = NA,
                        Dmsy2018 = NA,
                        Dlrp2018 = NA,
                        D2018 = NA,
                        OM    = "2016 Fit" ) %>%
                dplyr::select(  OM,
                                B0,
                                M_m,
                                M_f,
                                h,
                                B2016,
                                B2018,
                                Bmsy, Umsy, legUmsy, MSY,
                                D2016,  
                                Dmsy2016,
                                Dlrp2016, 
                                D2018,
                                Dmsy2018,
                                Dlrp2018 ) %>%
                cbind( mcmcProbLRP2016 )



# Start with var1var2mat, use covariance
# matrix to calculate distance from each
# centre
sampDist <- .6

subDists <- lapply( X = pairs, FUN = .mahalanobisDist,
                    post = mcmcDF, 
                    pars = c("h","spawnB54"),
                    qProb = c("mean","mean"),
                    mDist = sampDist ) 
subPosts <- subDists

for( i in 1:length(subPosts) )
{
  subPosts[[i]] <- left_join( subPosts[[i]], mcmcDF, by = c("h","spawnB54") )
  subPosts[[i]]$OM <- names(pairs)[i]
}

subPostOMs <- do.call(rbind,subPosts) %>%
            dplyr::select(  OM,
                            B0 = "SSB0",
                            M_m, 
                            M_f, 
                            h,
                            B2016 = spawnB52,
                            B2018 = spawnB54,
                            Bmsy, Umsy, legUmsy, MSY ) %>%
            mutate( D2016     = B2016/B0,
                    Dmsy2016  = B2016/Bmsy,
                    Dlrp2016  = B2016/(.4 * Bmsy),
                    D2018     = B2018/B0,
                    Dmsy2018  = B2018/Bmsy,
                    Dlrp2018  = B2018/(.4 * Bmsy) ) %>%
            group_by(OM) %>%
            summarise_if(is.numeric, summPostMeanSD) %>%
            mutate( ProbB2016GtLRP = NA,
                    ProbB2018GtLRP = NA )

write.csv(mcmcPostMean, file = "mcmcPostMean.csv")

write.csv(subPostOMs, file = "subPostOMs_stats.csv")

posteriorOMstats <- rbind(mcmc2016,mcmcPostMean,subPostOMs)

OMnames <- posteriorOMstats$OM
rownames(posteriorOMstats) <- OMnames
posteriorOMstats$OM <- NULL

fancyRowNames <- c( "$B_0$",
                    "$M_m$",
                    "$M_f$",
                    "$h$",
                    "$B_{2016}$",
                    "$B_{2018}$",
                    "$B_{MSY}$",
                    "$U_{MSY}$",
                    "Legal $U_{MSY}$",
                    "$MSY$",
                    "$B_{2016}/B_0$",
                    "$B_{2016}/B_{MSY}$",
                    "$B_{2016}/(.4B_{MSY})$",
                    "$B_{2018}/B_0$",
                    "$B_{2018}/B_{MSY}$",
                    "$B_{2018}/(.4B_{MSY})$",
                    "$P(B_{2016} \\geq .4B_{MSY})$",
                    "$P(B_{2018} \\geq .4B_{MSY})$")

posteriorOMstats <- t(posteriorOMstats)
rownames(posteriorOMstats) <- fancyRowNames

OMsummTableCap <- "Operating model posterior distribution mean (standard deviation) biological parameter, reference point estimates, and stock status indicators for fits to the 2016 data 
and 2018 data. The columns \\textbf{2016 Fit} and \\textbf{2018 Fit} show the mean and standard deviation of the full posterior for the respective fits, while the remaining columns just show posterior mean values 
from the 5 stratified regions for each productivity/biomass scenario. Stock status is shown relative to unfished ($B_t/B_0$), theoretical
most productive spawning biomass ($B_t/B_{MSY}$), and the limit reference point ($B_t/(.4B_{MSY})$) for $t \\in \\{2016, 2018\\}$. The bottom
two rows show the posterior probability of biomass being above the limit reference point in both 2016 and 2018."

postPairsDFcap <- "Posterior points used to define the 5 centres for the reference and robustness sets of operating models, around which each OM samples the posterior for historical period conditioning."

```

```{r, echo = FALSE, warning = FALSE, results = "as-is"}
csasdown::csas_table( posteriorOMstats,
                      caption = OMsummTableCap,
                      booktabs = TRUE, escape = FALSE,
                      landscape = TRUE,
                      font_size = 12, format = kable_format ) %>%
    kable_styling(  latex_options = c("hold_position", "scale_down"),
                    bootstrap_options = c("striped", "hover","scale_down"))
```

\newpage


```{r, echo = FALSE, include = FALSE, warning = FALSE}

# Ok, need to replace the _'s with \_ in all the MP names
texFriendlyUnderscore <- function(x = "blah_wah")
{
  split <- stringr::str_split(string = x, pattern = "_")

  reform <- paste( unlist(split), collapse = "\\_" )

  reform
}

# Replace passed objectives with a filled circle dot 
# (use unicode??)
passObj <- function( X, target = .95, comp = "gt" )
{
  out <- character(length = length(X))
  for( l in 1:length(X))
  { 
    if( length(target) > 1 )
      tar <- target[l]
    else tar <- target

    if( comp == "gt")
    {
      if( round(X,2) >= tar )
        out[l] <- paste("$\\bullet$")
      else out[l] <- paste("$",X,"<",target,"$",sep = "")
    }

    if( comp == "lt")
    {
      if( round(X,2) <= tar )
        out[l] <- paste("$\\bullet$")
      else out[l] <- paste("$",X,">",target,"$",sep = "")
    }    

  }
  return(out)
}


refOMobjTable <- read.csv("./data/hiRec_wtdTable_hiRecTuned.csv", header = TRUE, stringsAsFactors = FALSE ) %>%
                  dplyr::mutate(  Label = sapply( X = Label, FUN = texFriendlyUnderscore ))


refOMobjTable_robTune <- read.csv("./data/hiRec_wtdTable_simRecTuned.csv", header = TRUE, stringsAsFactors = FALSE ) %>%
                  dplyr::mutate(  Label = sapply( X = Label, FUN = texFriendlyUnderscore ))

                  

robOMobjTable <- read.csv("./data/simRec_wtdTable_simRecTuned.csv", header = TRUE, stringsAsFactors = FALSE ) %>%
                  dplyr::mutate(  Label = sapply( X = Label, FUN = texFriendlyUnderscore ))

robOMobjTable_refTune <- read.csv("./data/simRec_wtdTable_hiRecTuned.csv", header = TRUE, stringsAsFactors = FALSE ) %>%
                            dplyr::mutate(  Label = sapply( X = Label, FUN = texFriendlyUnderscore ))

SP_refTable <-  refOMobjTable %>%
                dplyr::arrange(desc(medAvgCatch)) %>%
                dplyr::select(  "MP", 
                                "Label", 
                                "ProbBtGtLRP", 
                                AcceptProbDec,
                                ObsProbDec,
                                ProbB2052GtBmsy,
                                "ProbCtLt1992",
                                "medAvgCatch",
                                "medAAV",
                                "C2019",
                                "D2019",
                                HR = inputF ) %>%
                dplyr::mutate(  AcceptProbDec = round(AcceptProbDec,2),
                                ProbBtGtLRP = round(ProbBtGtLRP,2),
                                ObsProbDec = round(ObsProbDec,2),
                                ProbB2052GtBmsy = round(ProbB2052GtBmsy,2),
                                ProbCtLt1992 = round(ProbCtLt1992,2),
                                medAvgCatch = round(medAvgCatch,3),
                                medAAV = round(medAAV),
                                C2019 = round(C2019,2),
                                D2019 = round(D2019,2),
                                HR = signif(HR,3) ) %>%
                dplyr::mutate(  pObj1     =  sapply(X = ProbBtGtLRP, FUN = passObj, target = .95),
                                pDecline  =  mapply(FUN = passObj, X = ObsProbDec, target = AcceptProbDec, comp = "lt") ,
                                pObj3     =  sapply(X = ProbB2052GtBmsy, FUN = passObj, target = .5) ) %>%
                dplyr::select(  "MP", 
                                "Label", 
                                "pObj1", 
                                "pDecline", 
                                "pObj3",
                                "ProbCtLt1992",
                                "medAvgCatch",
                                "medAAV",
                                "C2019",
                                "D2019",
                                HR )

SP_robTable <-  robOMobjTable %>%
                dplyr::arrange(desc(medAvgCatch)) %>%
                dplyr::select(  "MP", 
                                "Label", 
                                "ProbBtGtLRP", 
                                AcceptProbDec,
                                ObsProbDec,
                                ProbB2052GtBmsy,
                                "ProbCtLt1992",
                                "medAvgCatch",
                                "medAAV",
                                "C2019",
                                "D2019",
                                HR = inputF ) %>%
                dplyr::mutate(  AcceptProbDec = round(AcceptProbDec,2),
                                ProbBtGtLRP = round(ProbBtGtLRP,2),
                                ObsProbDec = round(ObsProbDec,2),
                                ProbB2052GtBmsy = round(ProbB2052GtBmsy,2),
                                ProbCtLt1992 = round(ProbCtLt1992,2),
                                medAvgCatch = round(medAvgCatch,3),
                                medAAV = round(medAAV),
                                C2019 = round(C2019,2),
                                D2019 = round(D2019,2),
                                HR = signif(HR,3) ) %>%
                dplyr::mutate(  pObj1     =  sapply(X = ProbBtGtLRP, FUN = passObj, target = .95),
                                pDecline  =  mapply(FUN = passObj, X = ObsProbDec, target = AcceptProbDec, comp = "lt"),
                                pObj3     =  sapply(X = ProbB2052GtBmsy, FUN = passObj, target = .5)) %>%
                dplyr::select(  "MP", 
                                "Label", 
                                "pObj1", 
                                "pDecline", 
                                "pObj3",
                                "ProbCtLt1992",
                                "medAvgCatch",
                                "medAAV",
                                "C2019",
                                "D2019",
                                HR )
                



informHeaders <- c( "No.",
                    "MP Label",
                    "$P(B_t \\geq .4B_{MSY})$",
                    "$P(Decline)$",
                    "$P(B_{2052} > B_{MSY})$",
                    "$P(C_t < 1.992)$",
                    "$\\bar{C}_{2019:2028}$",
                    "$AAV$",
                    "$C_{2019}$",
                    "$B_{2019}/B0$",
                    "$F_{2022}$" )


nOtherCols <- max(ncol(SP_refTable) - 7,0)

criteria <- c( " " = 2,
               "P > .95" = 1,
               "Obs < Acc" = 1,
               "P > .5" = 1,
               "min" = 1,
               "max" = 1,
               " " = nOtherCols)



objNames <- c(" " = 2,
              "Objective 1" = 1,
              "Objective 2" = 1,
              "Objective 3" = 1,
              "Objective 4" = 1,
              "Objective 5" = 1,
              "Other Important Quantities" = nOtherCols )

names(SP_refTable) <- informHeaders
names(SP_robTable) <- informHeaders

refOMtableCap <- "Weighted performance metrics for all candidate management procedures on the reference set of operating models, where recruitment is taken from the OM estimate for the 2015 year class. Conservation performance metrics that pass the criteria in the header are indicated by a bullet. Catch is given in biomass units, which are measured in kilotonnes. Table is sorted by 10 year average catch $\\bar{C}_{2019:2028}$. For Objective 2, Obs refers to the observed probability of decline, and Acc to the acceptable probability of decline, linearly interpolated between 0.05 at $0.4B_{MSY}$ and 0.5 at $B_{MSY}$."
robOMtableCap <- "Weighted performance metrics for all candidate management procedures on the robustness set of operating models, where recruitment is simulated stochastically off the stock-recruit curve for the 2015 year class. Conservation performance metrics that pass the criteria in the header are indicated by a bullet. Catch is given in biomass units, which are measured in kilotonnes. Table is sorted by 10 year average catch $\\bar{C}_{2019:2028}$. For Objective 2, Obs refers to the observed probability of decline, and Acc to the acceptable probability of decline, linearly interpolated between 0.05 at $0.4B_{MSY}$ and 0.5 at $B_{MSY}$."

```

```{r npvTables, echo = FALSE, include = FALSE, warning = FALSE}
NPV_refTable <-  refOMobjTable %>%
                dplyr::arrange(desc(medAvgCatch)) %>%
                dplyr::select(  "MP", 
                                "Label", 
                                "medAvgCatch",
                                npvC_trap,
                                npvC_LL,
                                npvC_trawl,
                                npvD_trap,
                                npvD_LL,
                                npvD_trawl,
                                vptC_trap,
                                vptC_LL,
                                vptC_trawl ) %>%
                dplyr::mutate_if( is.numeric, signif, 4 )

NPV_robTable <-  robOMobjTable %>%
                dplyr::arrange(desc(medAvgCatch)) %>%
                dplyr::select(  "MP", 
                                "Label", 
                                "medAvgCatch",
                                npvC_trap,
                                npvC_LL,
                                npvC_trawl,
                                npvD_trap,
                                npvD_LL,
                                npvD_trawl,
                                vptC_trap,
                                vptC_LL,
                                vptC_trawl ) %>%
                dplyr::mutate_if( is.numeric, signif, 4 )

npvHeaders <- c(  "No.",
                  "MP Label",
                  "$\\bar{C}_{2019:2028}$",
                  "$C^{trap}$",
                  "$C^{hook}$",
                  "$C^{trawl}$",
                  "$D^{trap}$",
                  "$D^{hook}$",
                  "$D^{trawl}$",
                  "$R^{trap}$",
                  "$R^{hook}$",
                  "$R^{trawl}$" )

npvUnits <- c(  " " = 2,
                  "Av. Catch (kt)" = 1,
                  "10 year revenue ($ millions)" = 6,
                  "Av. revenue ($/t)" = 3 )


colnames(NPV_robTable) <- npvHeaders
colnames(NPV_refTable) <- npvHeaders

refNPVcap <- "Weighted economic performance metrics for the first 10 years of the projections in the reference OM set. Column 3 shows the average catch over the first 10 years, and the remaining columns show the total value (\\$m) of catch $C$ and discards $D$ for all sectors, and the yearly average income $I$ in dollars per tonne of catch, over the next 10 years. All values are taken at 4 significant figures. Table is sorted by 10 year average catch $\\bar{C}_{2019:2028}$."
robNPVcap <- "Weighted economic performance metrics for the first 10 years of the projections in the robustness OM set. Column 3 shows the average catch over the first 10 years, and the remaining columns show the total value (\\$m) of catch $C$ and discards $D$ for all sectors, and the yearly average income $I$ in dollars per tonne of catch, over the next 10 years. All values are taken at 4 significant figures. Table is sorted by 10 year average catch $\\bar{C}_{2019:2028}$."

```



```{r,  echo = FALSE, warning =  FALSE }

csasdown::csas_table( SP_refTable, 
                      caption = refOMtableCap, 
                      format = kable_format, 
                      landscape =TRUE,
                      escape = FALSE, font_size = 9,
                      booktabs = TRUE,
                      align = c( "l","l",rep("c", ncol(SP_refTable) - 2 )) ) %>%
    kable_styling(  latex_options = c("hold_position", "scale_down"),
                     bootstrap_options = c("striped", "hover","scale_down")) %>%
    add_header_above( criteria,
                      bold = T ) %>%
    add_header_above( objNames,
                      bold = T )


```

\newpage

```{r, echo = FALSE, include = FALSE, warning = FALSE}
valTable <- read.csv("./data/sableValue.csv", header = TRUE, stringsAsFactors = FALSE)
```

```{r, echo = FALSE, warning = FALSE, results = "as-is"}
names(valTable) <- c("Weight Class (lb)", "Price (\\$/lb)" )
csasdown::csas_table( valTable,
                      caption = "Price per pound of sablefish in each weight class. Weight classes are defined by the limits of that class, in pounds (e.g., 2/3 is the class of fish between 2 and 3 pounds).",
                      booktabs = TRUE, escape = FALSE, 
                      font_size = 12, format = kable_format ) %>%
    kable_styling(  latex_options = c("hold_position", "scale_down"),
                    bootstrap_options = c("striped", "hover","scale_down"))

```

\newpage

```{r, echo = FALSE, results = "as-is"}
csasdown::csas_table( NPV_refTable, 
                      caption = refNPVcap, 
                      format = kable_format, 
                      landscape =TRUE,
                      escape = FALSE, font_size = 12,
                      booktabs = TRUE,
                      align  = c( "l","l",rep("c", ncol(SP_robTable) - 2 ))) %>%
    kable_styling(  latex_options = c("hold_position", "scale_down"),
                    bootstrap_options = c("striped", "hover","scale_down")) %>%
    add_header_above( npvUnits, bold = T)
```

\newpage

```{r,  echo = FALSE, warning =  FALSE }
csasdown::csas_table( SP_robTable, 
                      caption = robOMtableCap, 
                      format = kable_format, 
                      landscape =TRUE,
                      escape = FALSE, font_size = 9,
                      booktabs = TRUE,
                      align  = c( "l","l",rep("c", ncol(SP_robTable) - 2 ))) %>%
    kable_styling(  latex_options = c("hold_position", "scale_down"),
                    bootstrap_options = c("striped", "hover","scale_down")) %>%
    add_header_above( criteria, bold = T) %>%
    add_header_above( objNames,
                      bold = T )

```

\newpage



```{r, echo = FALSE, results = "as-is"}
csasdown::csas_table( NPV_robTable, 
                      caption = robNPVcap, 
                      format = kable_format, 
                      landscape =TRUE,
                      escape = FALSE, font_size = 12,
                      booktabs = TRUE,
                      align  = c( "l","l",rep("c", ncol(SP_robTable) - 2 ))) %>%
    kable_styling(  latex_options = c("hold_position", "scale_down"),
                    bootstrap_options = c("striped", "hover","scale_down")) %>%
    add_header_above( npvUnits, bold = T)
```



```{r, echo = FALSE, warning = FALSE, include = FALSE}
SP_robTableRefTune <-  robOMobjTable_refTune %>%
                        dplyr::arrange(desc(medAvgCatch)) %>%
                        dplyr::select(  "MP", 
                                        "Label", 
                                        "ProbBtGtLRP", 
                                        AcceptProbDec,
                                        ObsProbDec,
                                        ProbB2052GtBmsy,
                                        "ProbCtLt1992",
                                        "medAvgCatch",
                                        "medAAV",
                                        "C2019",
                                        "D2019",
                                        HR = inputF ) %>%
                        dplyr::mutate(  AcceptProbDec = round(AcceptProbDec,2),
                                        ProbBtGtLRP = round(ProbBtGtLRP,2),
                                        ObsProbDec = round(ObsProbDec,2),
                                        ProbCtLt1992 = round(ProbCtLt1992,2),
                                        ProbB2052GtBmsy = round(ProbB2052GtBmsy,2),
                                        medAvgCatch = round(medAvgCatch,3),
                                        medAAV = round(medAAV),
                                        C2019 = round(C2019,2),
                                        D2019 = round(D2019,2),
                                        HR = signif(HR,3) ) %>%
                        dplyr::mutate(  pObj1     =  sapply(X = ProbBtGtLRP, FUN = passObj, target = .95),
                                        pDecline  =  mapply(FUN = passObj, X = ObsProbDec, target = AcceptProbDec, comp = "lt"),
                                        pObj3     =  sapply(X = ProbB2052GtBmsy, FUN = passObj, target = .5)) %>%
                        dplyr::select(  "MP", 
                                        "Label", 
                                        "pObj1", 
                                        "pDecline", 
                                        "pObj3",
                                        "ProbCtLt1992",
                                        "medAvgCatch",
                                        "medAAV",
                                        "C2019",
                                        "D2019",
                                        HR )

SP_refTableRobTune <-  refOMobjTable_robTune %>%
                        dplyr::arrange(desc(medAvgCatch)) %>%
                        dplyr::select(  "MP", 
                                        "Label", 
                                        "ProbBtGtLRP", 
                                        AcceptProbDec,
                                        ObsProbDec,
                                        ProbB2052GtBmsy,
                                        "ProbCtLt1992",
                                        "medAvgCatch",
                                        "medAAV",
                                        "C2019",
                                        "D2019",
                                        HR = inputF ) %>%
                        dplyr::mutate(  AcceptProbDec = round(AcceptProbDec,2),
                                        ProbBtGtLRP = round(ProbBtGtLRP,2),
                                        ObsProbDec = round(ObsProbDec,2),
                                        ProbB2052GtBmsy = round(ProbB2052GtBmsy,2),
                                        ProbCtLt1992 = round(ProbCtLt1992,2),
                                        medAvgCatch = round(medAvgCatch,3),
                                        medAAV = round(medAAV),
                                        C2019 = round(C2019,2),
                                        D2019 = round(D2019,2),
                                        HR = signif(HR,3) ) %>%
                        dplyr::mutate(  pObj1     =  sapply(X = ProbBtGtLRP, FUN = passObj, target = .95),
                                        pDecline  =  mapply(FUN = passObj, X = ObsProbDec, target = AcceptProbDec, comp = "lt"),
                                        pObj3     =  sapply(X = ProbB2052GtBmsy, FUN = passObj, target = .5)) %>%
                        dplyr::select(  "MP", 
                                        "Label", 
                                        "pObj1", 
                                        "pDecline", 
                                        "pObj3",
                                        "ProbCtLt1992",
                                        "medAvgCatch",
                                        "medAAV",
                                        "C2019",
                                        "D2019",
                                        HR )

names(SP_robTableRefTune) <- informHeaders
names(SP_refTableRobTune) <- informHeaders

robOMtableCapRefTune <- "Weighted performance metrics for all candidate management procedures, with harvest rates tuned to performance on the reference set of operating models, and applied to the robustness set of operating models where recruitment is simulated stochastically off the stock-recruit curve for the 2015 year class. Conservation performance metrics that pass the criteria in the header are indicated by a bullet. Catch is given in biomass units, which are measured in kilotonnes. Table is sorted by 10 year average catch $\\bar{C}_{2019:2028}$. For Objective 2, Obs refers to the observed probability of decline, and Acc to the acceptable probability of decline, linearly interpolated between 0.05 at $0.4B_{MSY}$ and 0.5 at $B_{MSY}$."
refOMtableCapRobTune <- "Weighted performance metrics for all candidate management procedures, with harvest rates tuned to performance on the robustness set of operating models, and applied to the reference set of operating models accepting the high 2015 year class. Conservation performance metrics that pass the criteria in the header are indicated by a bullet. Catch is given in biomass units, which are measured in kilotonnes. Table is sorted by 10 year average catch $\\bar{C}_{2019:2028}$. For Objective 2, Obs refers to the observed probability of decline, and Acc to the acceptable probability of decline, linearly interpolated between 0.05 at $0.4B_{MSY}$ and 0.5 at $B_{MSY}$."
```

\newpage

```{r,  echo = FALSE, warning =  FALSE }
csasdown::csas_table( SP_robTableRefTune, 
                      caption = robOMtableCapRefTune, 
                      format = kable_format, 
                      landscape =TRUE,
                      escape = FALSE, font_size = 9,
                      booktabs = TRUE,
                      align  = c( "l","l",rep("c", ncol(SP_robTable) - 2 ))) %>%
    kable_styling(  latex_options = c("hold_position", "scale_down"),
                    bootstrap_options = c("striped", "hover","scale_down")) %>%
    add_header_above( criteria, bold = T) %>%
    add_header_above( objNames,
                      bold = T )

```

\newpage

```{r,  echo = FALSE, warning =  FALSE }
csasdown::csas_table( SP_refTableRobTune, 
                      caption = refOMtableCapRobTune, 
                      format = kable_format, 
                      landscape =TRUE,
                      escape = FALSE, font_size = 9,
                      booktabs = TRUE,
                      align  = c( "l","l",rep("c", ncol(SP_robTable) - 2 ))) %>%
    kable_styling(  latex_options = c("hold_position", "scale_down"),
                    bootstrap_options = c("striped", "hover","scale_down")) %>%
    add_header_above( criteria, bold = T) %>%
    add_header_above( objNames,
                      bold = T )

```



