\setcounter{table}{0}
# Les tables

```{r, echo = FALSE}

source(here::here("mseRtools.r"))

recDevYrs <- 10:52
recDevPad <- rep(0,recDevYrs[1]-1)

# read in mcmc output
mcmc    <- as.mcmc(read.table ("./data/mcoutMSY.dat", header = TRUE) )
mcmcDF  <- as.data.frame(mcmc)

# What two variables will we use, and what percentiles?
var1 <- "h"
var2 <- "spawnB54"
form <- paste(var2,"~",var1,sep = "")

var2Mat <- as.matrix(mcmc[,c(var1,var2)])


v1v2    <- lm ( as.formula(form), data = mcmcDF)
mean2d <- apply(X = var2Mat, FUN = mean, MARGIN = 2)
v1v2cov <- cov(var2Mat)

probs   <- c(0.1,0.9)
var1quants  <- quantile (mcmc[,var1], probs = probs)
v1m         <- mean (mcmc[,var1])
v2m         <- coef(v1v2)[1] + v1m*coef(v1v2)[2]

var2quants  <-  quantile(mcmc[,var2], probs=probs)

var2meanline  <-  coef(v1v2)[1] + var1quants*coef(v1v2)[2]

pairs <- list (   loB=c(v1m,var2quants[1]),
                  mhmB=c(v1m,v2m),
                  hiB=c(v1m,var2quants[2]),
                  loh=c(var1quants[1],var2meanline[1]),
                  hih=c(var1quants[2],var2meanline[2]))

pairsMat <- matrix(unlist(pairs),ncol = 2, byrow = TRUE)

densPairs <- lapply (  FUN = dmvnorm, X = pairs, mean = c(v1m,v2m),
                      sigma=v1v2cov)

densPairs <- as.numeric(densPairs)
densPairs <- signif(densPairs/sum(densPairs),3)
names(densPairs) <- names(pairs)

postPairsDF <- data.frame(  OM = names(pairs), 
                            Steepness= signif(pairsMat[,1],3),
                            B2018 = signif(pairsMat[,2],3),
                            density = densPairs )

rownames(postPairsDF) <- NULL

# Take mcmcDF, and turn into a table of posterior
# median estimates for
# B0, R0, M_f, M_m, h, B2019, Bmsy, Fmsy, MSY, B/Bmsy, B/B0

# calculate probability of being above LRP in 2018
# and 2016

mcmcProbLRP2018 <- mcmcDF %>%
                    mutate(OM = "Ajustement 2018") %>%
                    dplyr::select( OM,
                                    B2018 = spawnB54,
                                    B2016 = spawnB52,
                                    Bmsy ) %>%
                    mutate( B2018gtLRP = ifelse( B2018 >= .4*Bmsy, 1, 0 ),
                            B2016gtLRP = ifelse( B2016 >= .4*Bmsy, 1, 0 ) ) %>%
                    group_by( OM ) %>%
                    summarise( ProbB2016GtLRP = as.character(round(mean(B2016gtLRP),2)),
                               ProbB2018GtLRP = as.character(round(mean(B2018gtLRP),2)) ) %>%
                    dplyr::select(  ProbB2016GtLRP,
                                    ProbB2018GtLRP )


mcmcPostMean <- mcmcDF %>%
                mutate(OM = "Ajustement 2018") %>%
                dplyr::select(  OM,
                                B0 = "SSB0",
                                M_m, 
                                M_f, 
                                h,
                                B2016 = spawnB52,
                                B2018 = spawnB54,
                                Bmsy, Umsy, legUmsy, MSY ) %>%
                mutate( D2016     = B2016/B0,
                        Dmsy2016  = B2016/Bmsy,
                        Dlrp2016  = B2016/(.4*Bmsy),
                        D2018     = B2018/B0,
                        Dmsy2018  = B2018/Bmsy,
                        Dlrp2018  = B2018/(.4*Bmsy) ) %>%
                group_by(OM) %>%
                summarise_if( is.numeric, summPostMeanSD, se = TRUE ) %>%
                cbind( mcmcProbLRP2018 )
                

# read in mcmc output
mcmc2016    <- as.mcmc(read.table ("./data/mcoutMSY_2016.dat", header = TRUE) )

mcmcProbLRP2016 <- as.data.frame(mcmc2016) %>%
                    mutate(OM = "Ajustement 2016") %>%
                    dplyr::select( OM,
                                    B2016 = spawnB52,
                                    Bmsy ) %>%
                    mutate( B2016gtLRP = ifelse( B2016 >= .4*Bmsy, 1, 0 ) ) %>%
                    group_by( OM ) %>%
                    summarise( ProbB2016GtLRP = as.character(round(mean(B2016gtLRP),2)) ) %>%
                    mutate( ProbB2018GtLRP = NA ) %>%
                    dplyr::select(  ProbB2016GtLRP,
                                    ProbB2018GtLRP)


mcmc2016    <- as.data.frame(mcmc2016) %>%
                dplyr::select(  B0 = "SSB0",
                                M_m, 
                                M_f, 
                                h,
                                B2016 = spawnB52,
                                Bmsy, Umsy, legUmsy, MSY ) %>%
                mutate( Dmsy2016 = B2016/Bmsy,
                        Dlrp2016 = B2016/(.4*Bmsy),
                        D2016 = B2016/B0 ) %>%
                summarise_if( is.numeric, summPostMeanSD, se = TRUE ) %>%
                mutate( B2018 = NA,
                        Dmsy2018 = NA,
                        Dlrp2018 = NA,
                        D2018 = NA,
                        OM    = "Ajustement 2016" ) %>%
                dplyr::select(  OM,
                                B0,
                                M_m,
                                M_f,
                                h,
                                B2016,
                                B2018,
                                Bmsy, Umsy, legUmsy, MSY,
                                D2016,  
                                Dmsy2016,
                                Dlrp2016, 
                                D2018,
                                Dmsy2018,
                                Dlrp2018 ) %>%
                cbind( mcmcProbLRP2016 )



# Start with var1var2mat, use covariance
# matrix to calculate distance from each
# centre
sampDist <- .6

subDists <- lapply( X = pairs, FUN = .mahalanobisDist,
                    post = mcmcDF, 
                    pars = c("h","spawnB54"),
                    qProb = c("mean","mean"),
                    mDist = sampDist ) 
subPosts <- subDists

for( i in 1:length(subPosts) )
{
  subPosts[[i]] <- left_join( subPosts[[i]], mcmcDF, by = c("h","spawnB54") )
  subPosts[[i]]$OM <- names(pairs)[i]
}

subPostOMs <- do.call(rbind,subPosts) %>%
            dplyr::select(  OM,
                            B0 = "SSB0",
                            M_m, 
                            M_f, 
                            h,
                            B2016 = spawnB52,
                            B2018 = spawnB54,
                            Bmsy, Umsy, legUmsy, MSY ) %>%
            mutate( D2016     = B2016/B0,
                    Dmsy2016  = B2016/Bmsy,
                    Dlrp2016  = B2016/(.4 * Bmsy),
                    D2018     = B2018/B0,
                    Dmsy2018  = B2018/Bmsy,
                    Dlrp2018  = B2018/(.4 * Bmsy) ) %>%
            group_by(OM) %>%
            summarise_if(is.numeric, summPostMeanSD) %>%
            mutate( ProbB2016GtLRP = NA,
                    ProbB2018GtLRP = NA )

write.csv(mcmcPostMean, file = "mcmcPostMean.csv")

write.csv(subPostOMs, file = "subPostOMs_stats.csv")

#posteriorOMstats <- rbind(mcmc2016,mcmcPostMean,subPostOMs) # drop posterior strata so that table can be regular (instead of landscape) format
posteriorOMstats <- rbind(mcmc2016,mcmcPostMean)

OMnames <- posteriorOMstats$OM
rownames(posteriorOMstats) <- OMnames
posteriorOMstats$OM <- NULL

fancyRowNames <- c( "$B_0$",
                    "$M_m$",
                    "$M_f$",
                    "$h$",
                    "$B_{2016}$",
                    "$B_{2018}$",
                    "$B_{RMS}$",
                    "$U_{RMS}$",
                    "Legal $U_{RMS}$",
                    "$RMS$",
                    "$B_{2016}/B_0$",
                    "$B_{2016}/B_{RMS}$",
                    "$B_{2016}/(.4B_{RMS})$",
                    "$B_{2018}/B_0$",
                    "$B_{2018}/B_{RMS}$",
                    "$B_{2018}/(.4B_{RMS})$",
                    "$P(B_{2016} \\geq .4B_{RMS})$",
                    "$P(B_{2018} \\geq .4B_{RMS})$")

posteriorOMstats <- t(posteriorOMstats)
rownames(posteriorOMstats) <- fancyRowNames

#add dashes to blank cells for web accessability
posteriorOMstats[6,1] <- "-"
posteriorOMstats[14:16,1] <- c("-","-","-")
posteriorOMstats[18,1] <- "-"

OMsummTableCap <- "Paramètre biologique de la moyenne de répartition a posteriori du modèle d’exploitation (écart-type), estimations des points de référence et indicateurs de l’état des stocks aux fins des ajustements par rapport aux données de 2016 et de 2018. Les colonnes \\textbf{Ajustement 2016} et \\textbf{Ajustement 2018} montrent la moyenne et l’écart-type de la répartition globale a posteriori pour les ajustements respectifs. L’état des stocks est présenté par rapport à la biomasse du stock reproducteur ($B_t/B_{RMS}$) en théorie le plus productif de la population non exploitée ($B_t/B_0 $), et le point de référence limite ($B_t/(0,4B_{RMS})$) pour la valeur de $t \\in \\{2016, 2018\\}$. Les deux rangées du bas illustrent la probabilité a posteriori que la biomasse du stock reproducteur excède le point de référence limite en 2016 et en 2018."

# postPairsDFcap <- "Posterior points used to define the 5 centres for the reference and robustness sets of operating models, around which each OM samples the posterior for historical period conditioning."

```

```{r, echo = FALSE, warning = FALSE, results = "as-is"}
csasdown::csas_table( posteriorOMstats,
                      caption = OMsummTableCap,
                      booktabs = TRUE, escape = FALSE,
                      landscape = FALSE,
                      font_size = 12, format = kable_format ) %>%
    kable_styling(  latex_options = c("hold_position", "scale_down"),
                    bootstrap_options = c("striped", "hover","scale_down"))
```

\newpage


```{r, echo = FALSE, include = FALSE, warning = FALSE}

# Ok, need to replace the _'s with \_ in all the MP names
texFriendlyUnderscore <- function(x = "blah_wah")
{
  split <- stringr::str_split(string = x, pattern = "_")

  reform <- paste( unlist(split), collapse = "\\_" )

  reform
}

# Replace passed objectives with a filled circle dot 
# (use unicode??)
passObj <- function( X, target = .95, comp = "gt" )
{
  out <- character(length = length(X))
  for( l in 1:length(X))
  { 
    if( length(target) > 1 )
      tar <- target[l]
    else tar <- target

    if( comp == "gt")
    {
      if( round(X,2) >= tar )
        out[l] <- paste("$\\bullet$")
      else out[l] <- paste("$",X,"<",target,"$",sep = "")
    }

    if( comp == "lt")
    {
      if( round(X,2) <= tar )
        out[l] <- paste("$\\bullet$")
      else out[l] <- paste("$",X,">",target,"$",sep = "")
    }    

  }
  return(out)
}


refOMobjTable <- read.csv("./data/hiRec_wtdTable_hiRecTuned.csv", header = TRUE, stringsAsFactors = FALSE ) %>%
                  dplyr::mutate(  Label = sapply( X = Label, FUN = texFriendlyUnderscore ))


refOMobjTable_robTune <- read.csv("./data/hiRec_wtdTable_simRecTuned.csv", header = TRUE, stringsAsFactors = FALSE ) %>%
                  dplyr::mutate(  Label = sapply( X = Label, FUN = texFriendlyUnderscore ))

                  

robOMobjTable <- read.csv("./data/simRec_wtdTable_simRecTuned.csv", header = TRUE, stringsAsFactors = FALSE ) %>%
                  dplyr::mutate(  Label = sapply( X = Label, FUN = texFriendlyUnderscore ))

robOMobjTable_refTune <- read.csv("./data/simRec_wtdTable_hiRecTuned.csv", header = TRUE, stringsAsFactors = FALSE ) %>%
                            dplyr::mutate(  Label = sapply( X = Label, FUN = texFriendlyUnderscore ))

SP_refTable <-  refOMobjTable %>%
                dplyr::arrange(desc(medAvgCatch)) %>%
                dplyr::select(  "MP", 
                                "Label", 
                                "ProbBtGtLRP", 
                                AcceptProbDec,
                                ObsProbDec,
                                ProbB2052GtBmsy,
                                "ProbCtLt1992",
                                "medAvgCatch",
                                "medAvgTAC",
                                "medAAV",
                                "C2019",
                                "D2019",
                                HR = inputF ) %>%
                dplyr::mutate(  AcceptProbDec = round(AcceptProbDec,2),
                                ProbBtGtLRP = round(ProbBtGtLRP,2),
                                ObsProbDec = round(ObsProbDec,2),
                                ProbB2052GtBmsy = round(ProbB2052GtBmsy,2),
                                ProbCtLt1992 = round(ProbCtLt1992,2),
                                medAvgCatch = round(medAvgCatch,2),
                                medAvgTAC = round(medAvgTAC,2),
                                medAAV = round(medAAV),
                                C2019 = round(C2019,2),
                                D2019 = round(D2019,2),
                                HR = signif(HR,3) ) %>%
                dplyr::mutate(  pObj1     =  sapply(X = ProbBtGtLRP, FUN = passObj, target = .95),
                                pDecline  =  mapply(FUN = passObj, X = ObsProbDec, target = AcceptProbDec, comp = "lt") ,
                                pObj3     =  sapply(X = ProbB2052GtBmsy, FUN = passObj, target = .5) ) %>%
                dplyr::select(  "MP", 
                                "Label", 
                                "pObj1", 
                                "pDecline", 
                                "pObj3",
                                "ProbCtLt1992",
                                "medAvgCatch",
                                "medAvgTAC",
                                "medAAV",
                                "C2019",
                                "D2019",
                                HR )

SP_robTable <-  robOMobjTable %>%
                dplyr::arrange(desc(medAvgCatch)) %>%
                dplyr::select(  "MP", 
                                "Label", 
                                "ProbBtGtLRP", 
                                AcceptProbDec,
                                ObsProbDec,
                                ProbB2052GtBmsy,
                                "ProbCtLt1992",
                                "medAvgCatch",
                                "medAvgTAC",
                                "medAAV",
                                "C2019",
                                "D2019",
                                HR = inputF ) %>%
                dplyr::mutate(  AcceptProbDec = round(AcceptProbDec,2),
                                ProbBtGtLRP = round(ProbBtGtLRP,2),
                                ObsProbDec = round(ObsProbDec,2),
                                ProbB2052GtBmsy = round(ProbB2052GtBmsy,2),
                                ProbCtLt1992 = round(ProbCtLt1992,2),
                                medAvgCatch = round(medAvgCatch,2),
                                medAvgTAC = round(medAvgTAC,2),
                                medAAV = round(medAAV),
                                C2019 = round(C2019,2),
                                D2019 = round(D2019,2),
                                HR = signif(HR,3) ) %>%
                dplyr::mutate(  pObj1     =  sapply(X = ProbBtGtLRP, FUN = passObj, target = .95),
                                pDecline  =  mapply(FUN = passObj, X = ObsProbDec, target = AcceptProbDec, comp = "lt"),
                                pObj3     =  sapply(X = ProbB2052GtBmsy, FUN = passObj, target = .5)) %>%
                dplyr::select(  "MP", 
                                "Label", 
                                "pObj1", 
                                "pDecline", 
                                "pObj3",
                                "ProbCtLt1992",
                                "medAvgCatch",
                                "medAvgTAC",
                                "medAAV",
                                "C2019",
                                "D2019",
                                HR )
                



informHeaders <- c( "No.",
                    "PG étiquette",
                    "$P(B_t \\geq .4B_{RMS})$",
                    "$P(Décline)$",
                    "$P(B_{2052} > B_{RMS})$",
                    "$P(C_t < 1.992)$",
                    "$\\bar{C}_{2019:2028}$",
                    "$\\bar{TAC}_{2019:2028}$",
                    "$AAV$",
                    "$C_{2019}$",
                    "$B_{2019}/B0$",
                    "$F_{2022}$" )


nOtherCols <- max(ncol(SP_refTable) - 8,0)

criteria <- c( " " = 2,
               "P > .95" = 1,
               "Obs < Acc" = 1,
               "P > .5" = 1,
               "min" = 1,
               "max" = 1,
               "max" = 1,
               " " = nOtherCols)



objNames <- c(" " = 2,
              "Objective 1" = 1,
              "Objective 2" = 1,
              "Objective 3" = 1,
              "Objective 4" = 1,
              "Objective 5" = 2,
              "Autres quantités importantes" = nOtherCols )

names(SP_refTable) <- informHeaders
names(SP_robTable) <- informHeaders

refOMtableCap <- "Paramètres de pondération du rendement pour toutes les procédures de gestion examinées aux \\textbf{modèles d’exploitation de référence}. Les paramètres de rendement en matière de conservation qui répondent au critère de l’en-tête sont indiqués par une puce. La capture est représentée sous forme d’unités de biomasse mesurées en kilotonnes. Le tableau est trié en fonction des prises moyennes sur 10 ans $\\bar{C}_{2019:2028}$. Pour l’objectif 2, Obs fait référence à la probabilité observée d’un déclin, et Acc à la probabilité d’un déclin acceptable, avec interrelation de manière linéaire entre 0,05 à $0,4B_{RMS}$ et 0,5 à $B_{RMS}$."

robOMtableCap <- "Paramètres de pondération du rendement pour toutes les procédures de gestion examinées aux \\textbf{modèles d’exploitation de robustesse}. Les paramètres de rendement en matière de conservation qui répondent au critère de l’en-tête sont indiqués par une puce. La capture est représentée sous forme d’unités de biomasse mesurées en kilotonnes. Le tableau est trié en fonction des prises moyennes sur 10 ans $\\bar{C}_{2019:2028}$. Pour l’objectif 2, le terme Obs fait référence à la probabilité observée d’un déclin, et Acc à la probabilité d’un déclin acceptable, avec interrelation de manière linéaire entre 0,05 à $0,4B_{RMS}$ et 0,5 à $B_{RMS}$."

```

```{r npvTables, echo = FALSE, include = FALSE, warning = FALSE}
NPV_refTable <-  refOMobjTable %>%
                dplyr::arrange(desc(medAvgCatch)) %>%
                dplyr::mutate( totCatchRev = npvC_trap + npvC_LL + npvC_trawl ) %>%
                dplyr::select(  "MP", 
                                "Label", 
                                "medAvgCatch",
                                "medAvgTAC",
                                npvC_trap,
                                npvC_LL,
                                npvC_trawl,
                                npvD_trap,
                                npvD_LL,
                                npvD_trawl,
                                totCatchRev,
                                vptC_trap,
                                vptC_LL,
                                vptC_trawl ) %>%
                dplyr::mutate_if( is.numeric, signif, 4 )


NPV_robTable <-  robOMobjTable %>%
                dplyr::arrange(desc(medAvgCatch)) %>%
                dplyr::mutate( totCatchRev =npvC_trap + npvC_LL +npvC_trawl ) %>%
                dplyr::select(  "MP", 
                                "Label", 
                                "medAvgCatch",
                                "medAvgTAC",
                                npvC_trap,
                                npvC_LL,
                                npvC_trawl,
                                npvD_trap,
                                npvD_LL,
                                npvD_trawl,
                                totCatchRev,
                                vptC_trap,
                                vptC_LL,
                                vptC_trawl ) %>%
                dplyr::mutate_if( is.numeric, signif, 4 )

npvHeaders <- c(  "No.",
                  "PG étiquette",
                  "$\\bar{C}_{2019:2028}$",
                  "$\\bar{TAC}_{2019:2028}$",
                  "$C^{casier}$",
                  "$C^{crochet}$",
                  "$C^{chalut}$",
                  "$D^{casier}$",
                  "$D^{crochet}$",
                  "$D^{chalut}$",
                  "$C^{tot}$",
                  "$R^{casier}$",
                  "$R^{crochet}$",
                  "$R^{chalut}$" )

npvUnits <- c(  " " = 2,
                  "Av. Capture/TAC (kt)" = 2,
                  "10 année revenu ($ millions)" = 7,
                  "Av. revenu ($/t)" = 3 )


colnames(NPV_robTable) <- npvHeaders
colnames(NPV_refTable) <- npvHeaders

refNPVcap <- "Paramètres de pondération du rendement économique pour les 10 premières années de la prévision aux \\textbf{modèles d’exploitation de référence}. La colonne 3 illustre la prise moyenne au cours des 10 premières années, et les autres colonnes montrent le total des recettes cumulatives (\\$m) des prises $C$ et des remises à l’eau $D$ pour chaque secteur, les recettes produites par les prises $C^{tot}$ pour tous les secteurs combinés, et les recettes annuelles moyennes $R$ en dollars par tonne de poissons pris, au cours des 10 années suivantes. Toutes les valeurs incluent quatre chiffres significatifs. Le tableau est trié en fonction des prises moyennes sur 10 ans $\\bar{C}_{2019:2028}$"

robNPVcap <- "Paramètres de pondération du rendement économique pour les 10 premières années de la prévision à \\textbf{modèles d’exploitation de robustesse}. La colonne 3 illustre la prise moyenne au cours des 10 premières années, et les autres colonnes montrent le total des recettes cumulatives (\\$m) des prises $C$ et des remises à l’eau $D$ pour chaque secteur, les recettes produites par les prises $C^{tot}$ pour tous les secteurs combinés, et les recettes annuelles moyennes $R$ en dollars par tonne de poissons pris, au cours des 10 années suivantes. Toutes les valeurs incluent quatre chiffres significatifs. Le tableau est trié en fonction des prises moyennes sur 10 ans $\\bar{C}_{2019:2028}$."

```



```{r,  echo = FALSE, warning =  FALSE }

csasdown::csas_table( SP_refTable, 
                      caption = refOMtableCap, 
                      format = kable_format, 
                      landscape =TRUE,
                      escape = FALSE, font_size = 7,
                      booktabs = TRUE,
                      align = c( "l","l",rep("c", ncol(SP_refTable) - 2 )) ) %>%
    kable_styling(  latex_options = c("hold_position", "scale_down"),
                     bootstrap_options = c("striped", "hover","scale_down")) %>%
    add_header_above( criteria,
                      bold = T ) %>%
    add_header_above( objNames,
                      bold = T )


```

\newpage

```{r, echo = FALSE, include = FALSE, warning = FALSE}
valTable <- read.csv("./data/sableValue.csv", header = TRUE, stringsAsFactors = FALSE)
```

```{r, echo = FALSE, warning = FALSE, results = "as-is"}
names(valTable) <- c("Catégorie de poids (lb)", "Prix (\\$/lb)" )
csasdown::csas_table( valTable,
                      caption = "Prix par livre de morue charbonnière dans chaque catégorie de poids. Les catégories de poids sont définies par les limites de cette catégorie, en livres (p. ex. 2/3 est la catégorie de poissons pesant entre 2 et 3 livres).",
                      booktabs = TRUE, escape = FALSE, 
                      font_size = 12, format = kable_format ) %>%
    kable_styling(  latex_options = c("hold_position", "scale_down"),
                    bootstrap_options = c("striped", "hover","scale_down"))

```

\newpage

```{r, echo = FALSE, results = "as-is"}
csasdown::csas_table( NPV_refTable, 
                      caption = refNPVcap, 
                      format = kable_format, 
                      landscape =TRUE,
                      escape = FALSE, font_size = 10,
                      booktabs = TRUE,
                      align  = c( "l","l",rep("c", ncol(SP_robTable) - 2 ))) %>%
    kable_styling(  latex_options = c("hold_position", "scale_down"),
                    bootstrap_options = c("striped", "hover","scale_down")) %>%
    add_header_above( npvUnits, bold = T)
```

\newpage

```{r,  echo = FALSE, warning =  FALSE }
csasdown::csas_table( SP_robTable, 
                      caption = robOMtableCap, 
                      format = kable_format, 
                      landscape =TRUE,
                      escape = FALSE, font_size = 7,
                      booktabs = TRUE,
                      align  = c( "l","l",rep("c", ncol(SP_robTable) - 2 ))) %>%
    kable_styling(  latex_options = c("hold_position", "scale_down"),
                    bootstrap_options = c("striped", "hover","scale_down")) %>%
    add_header_above( criteria, bold = T) %>%
    add_header_above( objNames,
                      bold = T )

```

\newpage



```{r, echo = FALSE, results = "as-is"}
csasdown::csas_table( NPV_robTable, 
                      caption = robNPVcap, 
                      format = kable_format, 
                      landscape =TRUE,
                      escape = FALSE, font_size = 10,
                      booktabs = TRUE,
                      align  = c( "l","l",rep("c", ncol(SP_robTable) - 2 ))) %>%
    kable_styling(  latex_options = c("hold_position", "scale_down"),
                    bootstrap_options = c("striped", "hover","scale_down")) %>%
    add_header_above( npvUnits, bold = T)
```



```{r, echo = FALSE, warning = FALSE, include = FALSE}
SP_robTableRefTune <-  robOMobjTable_refTune %>%
                        dplyr::arrange(desc(medAvgCatch)) %>%
                        dplyr::select(  "MP", 
                                        "Label", 
                                        "ProbBtGtLRP", 
                                        AcceptProbDec,
                                        ObsProbDec,
                                        ProbB2052GtBmsy,
                                        "ProbCtLt1992",
                                        "medAvgCatch",
                                        "medAvgTAC",
                                        "medAAV",
                                        "C2019",
                                        "D2019",
                                        HR = inputF ) %>%
                        dplyr::mutate(  AcceptProbDec = round(AcceptProbDec,2),
                                        ProbBtGtLRP = round(ProbBtGtLRP,2),
                                        ObsProbDec = round(ObsProbDec,2),
                                        ProbCtLt1992 = round(ProbCtLt1992,2),
                                        ProbB2052GtBmsy = round(ProbB2052GtBmsy,2),
                                        medAvgCatch = round(medAvgCatch,2),
                                        medAvgTAC = round(medAvgTAC,2),
                                        medAAV = round(medAAV),
                                        C2019 = round(C2019,2),
                                        D2019 = round(D2019,2),
                                        HR = signif(HR,3) ) %>%
                        dplyr::mutate(  pObj1     =  sapply(X = ProbBtGtLRP, FUN = passObj, target = .95),
                                        pDecline  =  mapply(FUN = passObj, X = ObsProbDec, target = AcceptProbDec, comp = "lt"),
                                        pObj3     =  sapply(X = ProbB2052GtBmsy, FUN = passObj, target = .5)) %>%
                        dplyr::select(  "MP", 
                                        "Label", 
                                        "pObj1", 
                                        "pDecline", 
                                        "pObj3",
                                        "ProbCtLt1992",
                                        "medAvgCatch",
                                        "medAvgTAC",
                                        "medAAV",
                                        "C2019",
                                        "D2019",
                                        HR )

SP_refTableRobTune <-  refOMobjTable_robTune %>%
                        dplyr::arrange(desc(medAvgCatch)) %>%
                        dplyr::select(  "MP", 
                                        "Label", 
                                        "ProbBtGtLRP", 
                                        AcceptProbDec,
                                        ObsProbDec,
                                        ProbB2052GtBmsy,
                                        "ProbCtLt1992",
                                        "medAvgCatch",
                                        "medAvgTAC",
                                        "medAAV",
                                        "C2019",
                                        "D2019",
                                        HR = inputF ) %>%
                        dplyr::mutate(  AcceptProbDec = round(AcceptProbDec,2),
                                        ProbBtGtLRP = round(ProbBtGtLRP,2),
                                        ObsProbDec = round(ObsProbDec,2),
                                        ProbB2052GtBmsy = round(ProbB2052GtBmsy,2),
                                        ProbCtLt1992 = round(ProbCtLt1992,2),
                                        medAvgCatch = round(medAvgCatch,2),
                                        medAvgTAC = round(medAvgTAC,2),
                                        medAAV = round(medAAV),
                                        C2019 = round(C2019,2),
                                        D2019 = round(D2019,2),
                                        HR = signif(HR,3) ) %>%
                        dplyr::mutate(  pObj1     =  sapply(X = ProbBtGtLRP, FUN = passObj, target = .95),
                                        pDecline  =  mapply(FUN = passObj, X = ObsProbDec, target = AcceptProbDec, comp = "lt"),
                                        pObj3     =  sapply(X = ProbB2052GtBmsy, FUN = passObj, target = .5)) %>%
                        dplyr::select(  "MP", 
                                        "Label", 
                                        "pObj1", 
                                        "pDecline", 
                                        "pObj3",
                                        "ProbCtLt1992",
                                        "medAvgCatch",
                                        "medAvgTAC",
                                        "medAAV",
                                        "C2019",
                                        "D2019",
                                        HR )

names(SP_robTableRefTune) <- informHeaders
names(SP_refTableRobTune) <- informHeaders

robOMtableCapRefTune <- "Paramètres de pondération du rendement pour toutes les procédures de gestion examinées, et taux de récolte adaptés au rendement indiqué aux \\textbf{ modèles d’exploitation de référence}, et appliqués aux \\textbf{modèles d’exploitation de robustesse} où le recrutement est simulé de manière stochastique hors de la courbe stock-recrutement pour la classe de 2015. Les paramètres de rendement en matière de conservation qui répondent au critère de l’en-tête sont indiqués par une puce. La capture est représentée sous forme d’unités de biomasse mesurées en kilotonnes. Le tableau est trié en fonction des prises moyennes sur 10 ans $\\bar{C}_{2019:2028}$. Pour l’objectif 2, Obs fait référence à la probabilité observée d’un déclin, et Acc à la probabilité d’un déclin acceptable, avec interrelation de manière linéaire entre 0,05 à $0,4B_{RMS}$ et 0,5 à $B_{RMS}$."

refOMtableCapRobTune <- "Paramètres de rendement pondérés pour toutes les procédures de gestion proposées, avec des taux de récolte adaptés au rendement aux \\textbf{modèle d’exploitation de robustesse}, et appliqués aux \\textbf{modèles d’exploitation de référence}, en fonction de la classe d’âge élevée de 2015. Les paramètres de rendement en matière de conservation qui répondent au critère de l’en-tête sont indiqués par une puce. La capture est représentée sous forme d’unités de biomasse mesurées en kilotonnes. Le tableau est trié en fonction des prises moyennes sur 10 ans $\\bar{C}_{2019:2028}$. Pour l’objectif 2, Obs fait référence à la probabilité observée d’un déclin, et Acc à la probabilité d’un déclin acceptable, avec interrelation de manière linéaire entre 0,05 à $0,4B_{RMS}$ et 0,5 à $B_{RMS}$."

```

\newpage

```{r,  echo = FALSE, warning =  FALSE }
csasdown::csas_table( SP_robTableRefTune, 
                      caption = robOMtableCapRefTune, 
                      format = kable_format, 
                      landscape =TRUE,
                      escape = FALSE, font_size = 7,
                      booktabs = TRUE,
                      align  = c( "l","l",rep("c", ncol(SP_robTable) - 2 ))) %>%
    kable_styling(  latex_options = c("hold_position", "scale_down"),
                    bootstrap_options = c("striped", "hover","scale_down")) %>%
    add_header_above( criteria, bold = T) %>%
    add_header_above( objNames,
                      bold = T )

```

\newpage

```{r,  echo = FALSE, warning =  FALSE }
csasdown::csas_table( SP_refTableRobTune, 
                      caption = refOMtableCapRobTune, 
                      format = kable_format, 
                      landscape =TRUE,
                      escape = FALSE, font_size = 7,
                      booktabs = TRUE,
                      align  = c( "l","l",rep("c", ncol(SP_robTable) - 2 ))) %>%
    kable_styling(  latex_options = c("hold_position", "scale_down"),
                    bootstrap_options = c("striped", "hover","scale_down")) %>%
    add_header_above( criteria, bold = T) %>%
    add_header_above( objNames,
                      bold = T )

```



