# Contexte

Depuis 2008, Pêches et Océans Canada (MPO) et l'industrie de la pêche du poisson de fond en Colombie-Britannique collaborent à un processus d'évaluation des stratégies de gestion qui vise à maintenir une stratégie transparente et durable de pêche de la morue charbonnière dans la province. La transparence et la durabilité éventuelle des procédures de gestion proposées sont déterminées par des simulations qui mesurent ces procédures par rapport aux objectifs en matière de biologie et de pêche approuvés au préalable. Les modèles d'exploitation sur lesquels reposent les simulations visent à représenter les principales incertitudes liées à l'état des stocks de morue charbonnière et à la productivité. Le processus d'évaluation des stratégies de gestion de la morue charbonnière a fait l'objet de plusieurs examens par les pairs du Secrétariat canadien de consultation scientifique (SCCS) et de publications scientifiques indépendantes évaluées par les pairs [@cox2008practical;@cox2011management; @cox2013roles; @cox2019evaluating; @dfo2014performanc]. Depuis 2011, le MPO publie chaque année des avis sur la pêche canadienne de la morue charbonnière en fonction des simulations des procédures de gestion.

Le processus d'évaluation des stratégies de gestion de la morue charbonnière s'effectue tous les trois ans. Il permet de rajuster le modèle d'exploitation selon les dernières données sur les indices de la biomasse fondés sur les relevés et la pêche, les prises selon l'âge, les remises à l'eau, l'étiquetage et la recapture des poissons étiquetés. Chaque mise à jour triennale offre également l'occasion de modifier les objectifs de pêche et de proposer de nouvelles procédures de gestion.

Les évaluations antérieures de la morue charbonnière en Colombie-Britannique et les travaux en matière d'évaluation des stratégies de gestion ont démontré que le faible recrutement (en moyenne) au cours des trois dernières décennies a contribué au déclin à long terme de la biomasse du stock reproducteur et des possibilités de récolte. Les consultations auprès des intervenants et des gestionnaires ont révélé que la mortalité des poissons de taille inférieure à la taille réglementaire qui sont remis à l'eau (c.-à-d. les poissons de moins de 55 cm) pouvait être une source de mortalité dont la réduction ou l'évitement pourrait améliorer la production de morues charbonnières de plus de 55 cm, la biomasse du stock reproducteur et, finalement, les possibilités de récolte futures [@cox2019evaluating]. Bien que le processus d'évaluation de la stratégie de gestion de la morue charbonnière ait mentionné certaines mesures volontaires visant à réduire la mortalité des individus de petite taille (p. ex. une meilleure communication entre les flottilles et une surveillance électronique accrue), il n'a pas évalué officiellement les mesures de gestion visant à réduire la mortalité de ce type d'individus. Toutefois, les simulations antérieures en boucle fermée laissent supposer que l'évitement complet et la conservation complète des morues charbonnières de petite taille pourraient améliorer la production moyenne annuelle de l'espèce dans les pêches dirigées et rehausser la possibilité de rétablissement des stocks à $B_{RMS}$ [@cox2011management; @cox2019evaluating]. Malheureusement, l'évitement complet n'est peut-être pas possible, surtout dans les pêches au chalut, étant donné que des morues charbonnières de taille inférieure à la taille réglementaire y sont capturées pendant la pêche d'autres espèces. La conservation complète peut entraîner la perte de possibilités de pêche (particulièrement pour le secteur des pêches au chalut) et une rentabilité moindre pour les pêches dirigées, car les morues charbonnières de taille inférieure à la taille réglementaire valent moins par kilogramme que le poisson de taille réglementaire. Au cours des consultations, les intervenants de l'industrie ont indiqué qu'une solution possible consisterait à offrir des mesures incitant les pêcheurs à modifier leur comportement et à éviter davantage de pêcher des morues charbonnières de taille inférieure.

La Direction générale de la gestion des pêches du MPO a donc demandé à la Direction générale des sciences i) de mettre à jour le modèle d'exploitation de la morue charbonnière pour y inclure les données les plus récentes disponibles (jusqu'en 2018); ii) de mettre à jour les avis sur le rendement escompté de la procédure de gestion actuelle; et iii) d'évaluer d'autres procédures ou mesures de gestion ayant pour but de réduire les pertes de productivité en raison de la mortalité des individus de taille inférieure à la taille réglementaire. La question clé en iii) est de déterminer les procédures de gestion qui réduisent au minimum l'effet de telles mesures sur les possibilités de pêche dans le cadre des pêches non dirigées (c.-à-d. les pêches au chalut) où la morue charbonnière de taille inférieure est capturée accidentellement.

Les avis découlant de la présente réponse des Sciences du SCCS serviront à choisir une nouvelle procédure de gestion de la morue charbonnière pour 2020-2022, procédure qui sera conforme au Cadre pour la pêche durable du MPO et au Cadre décisionnel pour les pêches intégrant l'approche de précaution [@DFO2009]. De plus, la présente réponse des Sciences informe les gestionnaires des pêches et les intervenants des répercussions, sur le secteur des pêches, de l'atténuation des pertes de productivité en raison des remises à l'eau de morues charbonnières de taille inférieure à la taille réglementaire.

La présente réponse des Sciences découle du processus de réponse des Sciences du 23 septembre 2019 sur l'Évaluation de la performance de la stratégie de gestion alternative de la morue charbonnière en Colombie-Britannique, Canada.
