# Analyse et réponse

La présente réponse des Sciences a adopté une approche de simulation en boucle fermée pour évaluer le rendement relatif des procédures de gestion proposées pour la pêche de la morue charbonnière en Colombie Britannique, et a eu recours à une méthodologie identique à celle présentée dans le cycle précédent de l'évaluation des stratégies de gestion [@cox2019evaluating]. Les sous-sections qui suivent décrivent brièvement les données mises à jour qui ont servi à façonner le modèle d'exploitation de la morue charbonnière, les changements requis en fonction de ces données, et les nouveaux éléments de la procédure de gestion qui ont été mis à l'essai. D'autres détails sur les mécanismes de simulation, les vérifications diagnostiques et les calculs des mesures du rendement peuvent être consultés dans @cox2019evaluating.


La présente réponse des Sciences a pour but de :

1. décrire les ajustements et les inférences du modèle d'exploitation après sa modification en fonction des indices de biomasse à jour, des prises selon l'âge, et des nouvelles données sur les prises selon l'âge tirées de l'échantillonnage de la morue charbonnière pour déterminer sa composition selon la longueur dans la pêche au chalut;
2. établir à partir de ces données une grille de cinq modèles d'exploitation de référence et de cinq modèles de robustesse fondés sur les incertitudes associées à l'état et à la productivité des stocks de morue charbonnière (modèles d'exploitation de référence) et sur le recrutement pour l'année 2015 (modèles d'exploitation de robustesse);
3. mener des exercices de simulation des procédures de gestion proposées dans le cadre des modèles d'exploitation de référence et de robustesse en fonction du rendement par rapport aux objectifs de pêche (voir ci-dessous), et classer les procédures de gestion.


## Méthodes

### Mise à jour du modèle d'exploitation

Les données mises à jour jusqu'en 2018 comprenaient les indices de biomasse et les prises selon l'âge découlant du relevé aléatoire stratifié au casier, les prises selon l'âge pour la pêche commerciale au casier, ainsi que les prises et les remises à l'eau totales (en unités de biomasse) pour la pêche commerciale au casier, à la palangre et au chalut. Nous avons également obtenu de nouveaux ensembles de données sur les prises selon l'âge et selon la longueur pour la pêche au chalut afin d'aider à estimer la sélectivité des chaluts, qui est le déterminant clé des prises de morues charbonnières de taille inférieure à la taille réglementaire dans les pêches au chalut. L'ensemble complet des données sur les prises selon l'âge dans les pêches au chalut (avec quelques années manquantes) est fondé sur une clé âge-longueur créée à partir des données sur l'âge et la longueur recueillies de 1972 à 2017.

Le modèle d'exploitation a fait l'objet de légers changements dans le cadre des exercices réguliers visant à accroître l'harmonisation avec diverses données. Mentionnons entre autres i) la modification de la forme fonctionnelle de la sélectivité des chaluts à une fonction de densité gamma (figure A5); ii) la baisse de l'âge 3 à l'âge 2 pour la classe d'âge la plus jeune dans toutes les séries de composition d'âge afin de refléter la gamme des observations âge composition; iii) l'ajout de nouvelles données âge-composition pour la pêche au chalut (annexe A); iv) l'ajout d'un écart estimé du recrutement en 2015 au lieu de l'utilisation du recrutement escompté à partir de la courbe stock-recrutement; v) la mise à jour de la matrice des erreurs de détermination de l'âge afin d'utiliser une approximation normale plus simple, comme recommandé dans l'examen précédent du SCCS [@cox2019evaluating]; et vi) l'imposition d'un écart-type de $\sigma = 0,1$ (sur l'échelle logarithmique) aux erreurs d'observation relatives aux remises à l'eau dans le cadre de la pêche au chalut afin d'obtenir une meilleure correspondance à ces données. Les modèles précédents évitaient d'estimer le recrutement au cours des trois années précédentes, surtout parce que cette pratique aurait fourni les premières observations âge-mise à l'eau aux fins du modèle d'exploitation. De plus, il existe en général peu de renseignements pour justifier ces estimations étant donné que les poissons sont trop petits pour être sélectionnés par les pêches ou les relevés. Toutefois, aux fins de la présente mise à jour, le changement décrit en iv) ci-dessus a été retenu (c.-à-d. l'écart de recrutement estimé en 2015) parce qu'il fallait améliorer les correspondances avec les récentes observations de remises à l'eau (très élevées) dans les pêches au chalut. Autrement, nous simulerions les effets des remises à l'eau à partir d'un modèle qui ne correspond pas adéquatement aux remises à l'eau historiques. Ce changement pourrait avoir une incidence importante sur le rendement simulé de la procédure de gestion et, par conséquent, constitue le point central des modèles d'exploitation de robustesse (décrits ci dessous).


### Modèles d'exploitation examinés

#### Modèles d'exploitation de référence

Les modèles d'exploitation de référence ont été établis à l'aide de la même méthode que celle utilisée pour le cycle précédent de l'évaluation des stratégies de gestion [@cox2019evaluating]. En résumé, les cinq modèles d'exploitation ont été créés en fonction de la répartition conjointe a posteriori de la biomasse du stock reproducteur de 2018 (pour représenter le risque biologique à court terme) et de l'inclinaison de la pente de la relation stock-recrutement (pour représenter le risque de productivité à long terme des stocks). Les cinq combinaisons ont été choisies pour représenter la moyenne marginale conjointe de la biomasse et de l'inclinaison en 2018 et quatre points extérieurs à l'intersection de la moyenne d'une variable, ainsi que les 10e et 90e centiles de la densité marginale de l'autre variable (figure 1). Cet ensemble de cinq modèles d'exploitation a été choisi pour assurer la cohérence avec le cycle précédent de l'évaluation des stratégies de gestion [@cox2019evaluating]. Pour chacun des cinq points a posteriori, le modèle d'exploitation a été façonné par un échantillon de 100 sélections a posteriori devant se situer selon une distance de Mahalanobis à 0,75 unité par rapport à ce point. Une estimation empirique de la densité a posteriori a ensuite été appliquée à chacun des cinq centres comme cote de probabilité pour la pondération du rendement de la procédure de gestion, aux fins des cinq modèles d'exploitation pour chacun des ensembles de référence et de robustesse.

#### Modèles d'exploitation de robustesse

Les modèles d'exploitation de robustesse étaient identiques aux cinq modèles d'exploitation de référence, sauf en ce qui concerne la façon dont le recrutement pour la classe de 2015 était traité dans l'élaboration des modèles d'exploitation historiques et les projections. Les modèles d'exploitation de référence utilisés s'inspirent de la répartition conjointe a posteriori (comme elle est définie ci-dessus) pour la classe de 2015. Celle-ci correspond à environ 22 millions de poissons, soit environ 8 fois la moyenne historique. Pour ce qui est des modèles d'exploitation de robustesse, le recrutement a été simulé en fonction de la relation stock-recrutement découlant de la classe 2015 prévue, qui se rapprochait davantage de la moyenne à long terme ($\sim 2,63$ millions).

### Objectifs de pêche

Les objectifs pour la pêche de la morue charbonnière la Colombie-Britannique ont été mis au point progressivement au cours des dix dernières années grâce à des consultations entre les gestionnaires de pêche, les scientifiques et les intervenants de l'industrie [@cox2009evaluation; @cox2011management; @dfo2014performanc; @cox2019evaluating]. Les cinq principaux objectifs qui guident cette pêche sont les suivants :

1. **P(fBSR > PRL)** : Maintenir la biomasse du stock reproducteur femelle (SRF) au-dessus du point de référence limite $PRL = 0,4B_{RMS}$, où $B_{RMS}$ représente le modèle d'exploitation de la biomasse du stock reproducteur femelle équivalant à un rendement maximal durable ($RMS$), pour 95 % des années mesurées sur deux générations de morues charbonnières (36 ans).
2. **P(déclin)** : Lorsque la biomasse du stock reproducteur femelle se situe entre $0,4B_{RMS}$ et $0,8B_{RMS}$, limiter la probabilité d'un déclin au cours des 10 prochaines années d'un taux très faible (5 %) de $0,4B_{RMS}$ à un taux modéré (50 %) de $0,8B_{RMS}$. À des niveaux intermédiaires de l'état du stock, définir la tolérance au déclin par une polarisation linéaire entre ces probabilités.
3. **P(fBSR > B_$B_{RMS}$)** : Maintenir la biomasse du stock reproducteur femelle au-dessus du niveau cible de a) $B_{RMS}$ à l'intérieur de la zone saine, ou de b) $0,8B_{RMS}$ au moment du rétablissement de la zone de prudence en 2052, avec une probabilité de 50 %.
4. **P(TAC < 1 992 t)** : Réduire le plus possible la probabilité que les niveaux annuels du total autorisé des captures (TAC) soient inférieurs à 1 992 tonnes pendant deux générations de morue charbonnière.
5. **Prises maximales** : Optimiser les prises annuelles moyennes sur 10 ans, sous réserve des objectifs 1 à 4.

Les mesures de rendement correspondant aux objectifs de pêche 1 à 4 (en gras) s'expriment en tant que « probabilité de (condition) ». Les mesures de rendement sont calculées pour chaque reproduction de simulation, et le rendement escompté pour une procédure de gestion est résumé par la moyenne (ou la médiane) des 100 reproductions de chaque simulation. Les détails complets des mesures de rendement et des calculs sont présentés dans @cox2019evaluating.

Tel qu'il a été mentionné précédemment, il y a une bonification de prix pour les classes de morues charbonnières de plus grande taille, ce qui signifie que le même tonnage de prises débarquées peut donner des valeurs très différentes à quai si les répartitions sous-jacentes des poissons selon la taille varient grandement. Cette situation peut avoir des conséquences sur les mesures de gestion des individus de taille inférieure à la taille réglementaire, qui exigent le débarquement de petites morues charbonnières (sans limite de taille). Par conséquent, en plus de présenter des statistiques sur le rendement des prises (objectif de pêche 5), l'évaluation a calculé les recettes cumulatives sur 10 ans et le revenu moyen par tonne pour chaque flottille (parce que la composition des prises en fonction des tailles varie également selon la flottille).


### Procédures de gestion

Une procédure de gestion s'entend d'un algorithme précis et reproductible servant à calculer le total autorisé des captures (TAC) annuel pour une catégorie de pêche. Dans la plupart des cas, les procédures de gestion comprennent des données de surveillance, des méthodes d'évaluation pour le traitement des données et l'estimation de l'état des stocks, des règles de contrôle de la récolte pour traduire les extrants de l'évaluation en limites de prises, des métarègles qui peuvent inclure des contraintes sur les changements des TAC, ainsi que des conditions (p. ex. circonstances exceptionnelles) pour déclencher des déviations par rapport à l'avis habituel sur la récolte des procédures de gestion.

La procédure de gestion qui sert actuellement à calculer le TAC pour la morue charbonnière a été établie pour la première fois en 2011, puis modifiée à l'occasion des deux versions subséquentes de l'évaluation des stratégies de gestion. En général, la procédure de gestion inclut i) des __données__ - prises débarquées et trois indices de la biomasse; ii) une __méthode d'évaluation__ - un modèle de production excédentaire comportant des erreurs d'observation et de processus afin d'estimer la biomasse du stock à partir des indices de la biomasse et des prises débarquées; iii) un __rapport de contrôle de la récolte__ - un rapport 60:40 au titre du contrôle de la récolte selon lequel le taux de récolte cible est rajusté à partir de 0 % lorsque la biomasse estimée est inférieure à 40 % de $B_{RMS}$ à une valeur maximale lorsque la biomasse estimée est supérieure à 60 % de la valeur $B_{RMS}$ estimée; iv) une __métarègle__ - précisant que les hausses du TAC sont nulles à moins que le rapport de contrôle de la récolte recommande une augmentation de plus de 200 tonnes (les diminutions du TAC sont toujours adoptées); et v) une __métarègle__ - ramenant le taux maximal cible de mortalité des poissons de 9,5 % en 2017 à 5,5 % en 2021. Les TAC sont répartis entre les trois secteurs ainsi : 40,37 % pour le casier, 50,90 % pour la palangre et 8,75 % pour le chalut; les quotas restants sont réservés aux relevés. La production attribuée à la pêche au chalut découle de négociations entre les secteurs qui ont fixé l'attribution des prises en fonction des évaluations précédentes des stratégies de gestion [@cox2011management], tandis que les prises allouées à la pêche à la palangre et à celle au chalut sont calculées en fonction de la part moyenne des prises dans chaque secteur au cours de la période de 2009 à 2018.

La présente réponse des Sciences repose sur l'évaluation du rendement de la procédure de gestion actuelle pour la morue charbonnière, un scénario de référence où la population n'est pas exploitée, et 15 versions de la procédure actuelle où seules les mesures de gestion des remises à l'eau varient. Les versions de la procédure de gestion sont établies par la combinaison de trois éléments :

1. le __plafond de remises à l'eau des poissons de taille inférieure à la taille réglementaire__, qui prévoit que toutes les remises à l'eau sous le plafond peuvent être relâchées sans pénalité et que le nombre de prises excédant le plafond est classé dans les excédents. Les valeurs de plafond sont les suivantes : aucun plafond, 0 %, 50 %, 100 % et 150 % de plus que la moyenne de 464 t de remises à l'eau entre 2006 et 2018. La procédure de gestion actuelle ne comporte aucun plafond (remises à l'eau illimitées sans pénalité), alors que l'option sans limite de taille (**SLT**) ne permet aucune remise à l'eau (tous les poissons amenés à bord des navires doivent être débarqués et comptés dans le TAC).
2. des __allocations fixes pour les différentes flottilles__ (c.-à-d. casier, palangre et chalut) par rapport au plafond des remises à l'eau. Les allocations sont calculées en fonction de la moyenne des parts récentes (rct = $(23 \%, 18 \%, 59 \%)$, 2016-2018) ou historiques (hst = $(30 \%, 37 \%, 33 \%)$, 2006-2018) du total des remises à l'eau annuelles qui ont été attribuées à chaque flottille.
3. une __période d'amortissement __ de 5 (am5) ou 10 (am10) ans au cours de laquelle il faut étaler les excédents des remises à l'eau par rapport aux TAC futurs.

Dans la présente réponse des Sciences, les procédures de gestion sont désignées par la combinaison de trois mesures de gestion en mer décrites ci-dessus : PLAFOND_ALLOCATION_AMORTISSEMENT. Par exemple, la procédure de gestion  **cap.5_hstAl_am5** comporte un plafond des remises à l'eau totales fixé à 50 % (0,5) de la moyenne historique (**cap.5**), une allocation du plafond entre les flottilles fondée sur les parts moyennes historiques qui s'appliquent à chaque flottille (**hstAl**), et une période d'amortissement de cinq ans pour les excédents de remises à l'eau (**am5**). Les deux cas spéciaux de cette convention d'affectation des noms sont : la procédure de gestion actuelle (**sans plafond**), qui ne comporte aucun plafond, et celle sans limite de taille (**SLT**), qui ne permet aucune remise à l'eau (toutes les prises sont débarquées quelle que soit leur taille). Pour les plafonds de 0 %, seule la période d'amortissement pour les excédents s'appliquerait (p. ex. **cap0_am5**), et toutes les remises à l'eau seraient comptées comme des excédents.

#### Un exemple pratique des mesures de gestion des remises à l'eau dans le scénario **cap.5_hstAl_am5**

Pour illustrer comment ont été établies les simulations de mise en ouvre des mesures de gestion des remises à l'eau, la séquence des calculs utilisés pour déterminer les plafonds annuels de remises à l'eau est présentée ci-dessous, de même que leurs effets sur les allocations futures du TAC. Dans les calculs ci-dessous, $t$ correspond à l'année, $g$ à la flottille, et $p(g)$ à la part des remises à l'eau attribuée à la flottille $g$.

1. Calculer 50 % du PLAFOND des remises à l'eau par année et par flottille (464 t est la moyenne de 2006 à 2018) :
\begin{equation*} 
CAP(t,g) = 0,5 \cdot 0,464 \cdot p(g). 
\end{equation*}
2. Exécuter la simulation pour l'année t afin d'obtenir les remises à l'eau réelles : $R(t,g)$.
3. Calculer l'excédent $o(t,g)$ pour l'année en établissant la différence entre les remises à l'eau réelles $R(t,g)$ et le plafond $CAP(t,g)$ : \tabularnewline
\begin{equation*} 
o(t,g) = R(t,g) - CAP(t,g).
\end{equation*}
4. Étant donné que la période d'amortissement est de 5 ans, ajouter 1/5e de l'excédent de cette année au cumulatif des excédents $O(t+k,g)$ de chacune des cinq années qui suivent :
\begin{equation*}
O(t + k,g) = O(t+k,g) + o(t,g)/5, \mbox{ pour } k = 1, ..., 5.    
\end{equation*}
5. Calculer le TAC rajusté pour la morue charbonnière de taille réglementaire qui vaudra pour l'année prochaine en soustrayant le total de l'excédent pour l'année en question du $TAC'S initial ($TAC'S fixé par la procédure de gestion avant les mesures de gestion des remises à l'eau) :
\begin{equation*}
TAC(t,g) = TAC'(t,g) - O(t,g).
\end{equation*}


Cette méthode vise à inciter les pêcheurs à ne pas prendre de morues charbonnières de taille inférieure à la taille réglementaire grâce aux réductions futures du TAC (en supposant un rapprochement un-pour-un de la biomasse des individus de taille inférieure à celle des morues charbonnières de taille réglementaire), tout en permettant une certaine souplesse d'une année à l'autre pour les remises à l'eau importantes et imprévisibles au cours d'une année donnée. Il est à noter que les excédents ne peuvent jamais être inférieurs à zéro, de sorte que les TAC ne peuvent être relevés au-delà du TAC initial établi par la procédure de gestion de premier palier (c.-à-d. qu'il ne peut y avoir de mise en banque des TAC).

### Ajustement des procédures de gestion

L'évaluation de la stratégie de gestion de la morue charbonnière quantifie le rendement des procédures de gestion par rapport aux statistiques sur le rendement qui correspondent à chacun des objectifs de pêche. Les trois premières statistiques sur le rendement sont représentées par le rendement de la conservation de la biomasse par rapport au point de référence limite (PRL), la probabilité d'un déclin à court terme et l'atteinte complète ou partielle d'une cible à long terme de $B_{RMS}$, tandis que les quatrième et cinquième statistiques ont trait au maintien des niveaux de prises au-dessus d'un plancher privilégié par l'industrie et des prises moyennes à court terme. Il est rare que deux procédures de gestion affichent un rendement comparable pour quatre de ces statistiques de rendement et diffèrent à l'égard d'une seule. Si c'était le cas, la décision sur la procédure de gestion préférée serait simple - il s'agirait de choisir celle qui affiche le meilleur rendement pour la cinquième statistique. Malheureusement, les procédures de gestion diffèrent généralement sur les cinq statistiques de rendement simultanément, de sorte qu'il est difficile de comparer le rendement sans, à tout le moins, établir une certaine équivalence entre les probabilités de conservation (objectifs de pêche 1 à 3) et les prises moyennes à court terme (objectif de pêche 5).

L'ajustement des procédures de gestion est un moyen d'en établir le rendement équivalent par rapport aux objectifs pour lesquels les valeurs et les probabilités sont bien établies. Par exemple, le maintien du stock de morue charbonnière au-dessus du PRL ($0,4B_{RMS}$) avec une forte probabilité n'a pas fait l'objet d'un débat ouvert puisqu'il s'agit d'une directive générale canadienne dans le contexte de la pêche à la morue charbonnière (du moins, il n'y a pas eu de débat au cours des 10 ans et plus d'existence de l'évaluation des stratégies de gestion de la morue charbonnière). De même, le maintien d'une faible probabilité de déclin à court terme n'a pas non plus fait l'objet d'un débat, probablement parce que l'objectif principal de l'industrie de la pêche à la morue charbonnière a été d'éviter un nouveau déclin depuis le début du processus d'évaluation des stratégies de gestion. L'objectif de pêche 3 - la biomasse du stock reproducteur dans la zone saine d'ici deux générations - a été débattu au fil des ans pour des raisons pratiques. Plus précisément, on craint que l'atteinte de l'objectif de pêche 3 ne nécessite de sévères restrictions des prises à court terme pour des avantages à long terme très incertains. Au cours de l'année écoulée, l'industrie de la morue charbonnière et le MPO ont convenu de modifier l'objectif de pêche 3 pour obtenir la biomasse dans la zone saine d'ici la fin d'une année précise (2052) avec une probabilité d'au moins 50 %, c.-à-d. une valeur médiane de la biomasse du stock reproducteur femelle égale ou supérieure à $B_{RMS}$. Comme nous le démontrons ci-dessous, cet objectif est maintenant réalisable compte tenu de la dynamique de la morue charbonnière et de l'éventail de procédures de gestion réalistes. Toutefois, une nouvelle question se pose à cet égard : Que vaut l'amélioration (c.-à-d. en prises) du rendement au chapitre de l'objectif de pêche 3; par exemple, P$ (B_{2052} \ geq B_{RMS}) = 0,5 $ à P$ (B_{2052} \ geq B_{RMS}) = 0,55 $? Un écart de probabilité de seulement cinq points de pourcentage pourrait signifier une différence de plusieurs centaines de tonnes de prises annuelles moyennes, et des dizaines de millions de dollars en revenus. Les procédures de gestion qui affichent un meilleur rendement relativement à l'objectif de pêche 3 le font presque toujours au détriment du rendement relatif aux objectifs de pêche 4 et 5.

On a tenté de simplifier l'interprétation du rendement des procédures de gestion en les harmonisant toutes avec la formule standard $P(B_{2052} \geq B_{RMS}) = 0,5$, de sorte que toutes les procédures atteignent les objectifs 1 à 3. Cette harmonisation a été faite par des mises au point progressives de $F_{2021}$, qui correspond au taux de mortalité maximal de la pêche ciblée pour l'année 2021 (dans le cadre d'une période progressive de 5 ans pour la procédure actuelle) [@cox2019evaluating], jusqu'à ce que chaque procédure atteigne l'objectif 3, c.-à-d. $P(B_{2052} \geq B_{RMS}) = 0,5$. Ces taux cibles de prises maximales $F_{2021}$ remplacent alors les taux cibles de prises maximales prévus de 5,5 % pour l'année 2022 et les années suivantes.

Chaque procédure de gestion a été ajustée séparément avec les scénarios des modèles d'exploitation de référence et de robustesse, ce qui a donné des valeurs différentes $F_{2021}$ (c.-à-d. une pour chaque modèle d'exploitation). Nous avons ensuite simulé un test croisé dans lequel des valeurs $F_ {2021}$ ajustées selon le modèle d'exploitation de référence ont été appliquées aux procédures de gestion des modèles d'exploitation de robustesse et vice versa. Le test croisé révèle les conséquences biologiques et de capture que peut avoir l'utilisation des mauvaises valeurs $F_{2021}$.

## Résultats

### Mise à jour du modèle d'exploitation et répercussions sur l'état des stocks

Les adaptations du modèle d'exploitation en fonction du relevé et des indices de la biomasse de la pêche étaient semblables à celles des versions précédentes, où le modèle et les données montraient un déclin constant à long terme. Les points de données des deux relevés aléatoires stratifiés les plus récents (2017 et 2018) étaient considérablement plus élevés que ceux des 15 années précédentes, ce qui laisse entrevoir des augmentations éventuelles de la biomasse des stocks extracôtiers (figure 2).

En général, le modèle d'exploitation structuré selon l'âge correspond assez bien aux données sur la composition par âge (figure 3). La composition par âge de la pêche au casier a continué de montrer une importante différence résiduelle positive chez les mâles de 35 ans et plus et, dans une mesure plus négligeable, chez les femelles (figure 3 - Casier :). La composition par âge de la pêche au chalut a également montré une importante différence résiduelle positive pour les mâles de 2 ans qui semble découler des vastes échantillons de 2017 et de 2018 et, par conséquent, a eu tendance d'entraîner une moyenne qui semble présenter une importante différence résiduelle positive à 2 ans. Il s'agissait d'un élément pouvant déterminer la taille estimative de la classe de l'année 2015.

Le modèle correspondant au relevé normalisé était similaire aux versions précédentes des modèles d'exploitation - les tendances se situent quelque part entre les ajustements de la composition par âge (pire) et les ajustements du relevé aléatoire stratifié au casier (meilleure) [figures 2 et 3]. Le modèle d'exploitation continue de très bien correspondre au relevé aléatoire stratifié au casier, probablement parce que celui-ci est conçu spécialement pour surveiller la population extracôtière de morue charbonnière (contrairement à tous les autres ensembles de données).

La mise à jour de l'état des stocks de morue charbonnière canadienne dépendait de la taille absolue de la classe d'âge de 2015 (3 ans au cours de l'année d'évaluation 2018). L'estimation brute de cette classe était d'environ huit fois la moyenne historique (voir la section ci-dessus sur les modèles d'exploitation de robustesse - figure 4, dernière rangée), ce qui a donné l'impression qu'il s'agissait du plus important recrutement d'une population alors que les biomasses du stock reproducteur étaient à leur plus bas. Un recrutement aussi élevé avec une biomasse du stock reproducteur faible a eu des effets en cascade sur les estimations des paramètres du modèle, les points de référence biologiques et l'estimation de la biomasse actuelle. Ces effets comprenaient : i) la productivité estimative des stocks (c.-à-d. le paramètre d'inclinaison de la pente de la relation stock-recrutement) a été rajustée à la hausse; ii) la taille du stock le plus productif ($B_{RMS}$) a été rajustée à la baisse, parce que le stock est semble-t-il plus productif lorsque la biomasse est faible; iii) le taux optimal de mortalité des poissons ($F_{RMS}$) a été relevé parce que le stock plus productif peut subir des pressions supérieures sur le plan de la pêche; et iv) la biomasse actuelle du stock reproducteur a été rajustée à la hausse parce qu'environ 20 à 25 % des poissons âgés de 3 ans arrivaient à maturité.  Bien qu'il s'agisse de signes positifs et encourageants qui indiquent que l'état de la morue charbonnière s'améliore, il y avait un certain risque à harmoniser les procédures de gestion futures avec les changements importants apportés au modèle par suite d'un petit nombre d'observations. D'autres pêches de poisson de fond du Pacifique (p. ex. le merlu du Pacifique [*Merluccius productus*] et la morue charbonnière du golfe de l'Alaska) ont traité avec circonspection les premières estimations importantes en matière de recrutement tant que les données utilisées pour les estimer ne se matérialiseront pas davantage. Dans le présent cas, l'incertitude quant à la taille des classes de 2015 a été contrée par l'élaboration de modèles d'exploitation de référence (qui utilisent les données relatives à l'âge 3) et de robustesse (qui ne tiennent pas compte des données relatives à l'âge 3) qui serviraient à l'évaluation des procédures de gestion.

En ce qui concerne la grande classe de 2015, le modèle d'exploitation ajusté a révélé que le stock de morue charbonnière était généralement bon (tableau 1, 2018 - Ajustement). En 2018, la biomasse du stock reproducteur était environ deux fois plus élevée que le point de référence limite (PRL), comparativement à environ 1,5 fois le PRL, qui a lui-même été relevé par rapport à l'ajustement de 2016 qui était d'environ 1,17 fois le PRL. Ce changement indique que les stocks de morue charbonnière de la Colombie-Britannique ne font peut-être plus l'objet d'une surpêche. De même, la probabilité a posteori que la biomasse de l'année précédente soit supérieure au point de référence limite s'est également améliorée de 2016 à 2018, passant de 93 % (ajustement en 2016) à 100 % (ajustement en 2018).

### Résultats de l'évaluation des procédures de gestion

#### Modèles d'exploitation de référence établis en fonction de l'ajustement $F_{2021}$

Comme on s'y attendait, le recrutement de la classe de 2015 a été le principal déterminant de la biomasse estimée du stock reproducteur et des résultats de la pêche projetés dans les simulations du modèle d'exploitation de référence. La biomasse du stock reproducteur s'est accrue rapidement au cours des cinq premières années de la période de prévision (c.-à-d. la classe de 2015), car les poissons âgés de 3 ans ont été entièrement recrutés pour la pêche, puis pour la biomasse du stock recruteur (figures 4 et 5, première rangée). La biomasse du stock recruteur a ensuite connu une tendance à la baisse pour atteindre $B_{RMS}$ à long terme, car les poissons de la classe de 2015 ont été pêchés et les recrutements sont revenus aux valeurs prévues conformément à la relation stock-recrutement (c.-à-d. les recrutements à partir de 2016 sont tous simulés selon la relation stock-recrutement).

Dans ces conditions, toutes les procédures de gestion respectaient tous les critères biologiques définis dans les objectifs de pêche 1 à 3 (tableau 2). Toutes les procédures de gestion ajustées ont été en mesure d'atteindre l'objectif de pêche 3, alors que la biomasse du stock reproducteur médiane (première rangée de la figure 5) atteindra $B_{RMS}$ (ligne pointillée horizontale avec des points verts aux extrémités) d'ici la dernière année (2052). Certaines procédures de gestion pourront atteindre $B_{RMS}$ 15 à 20 ans avant la dernière année, tandis que d'autres arriveront tout juste à réaliser $B_{RMS}$ la dernière année.

L'ajustement des procédures de gestion (PG) pour qu'elles respectent les objectifs 1 à 3, et plus particulièrement le fait de traiter l'objectif de pêche 3 comme une cible, axent les écarts de rendement des procédures de gestion sur les prises annuelles moyennes au cours des 10 prochaines années (tableau 2 - Objectif 5). Comme prévu, les procédures de gestion comportant des mesures de gestion des remises à l'eau plus restreintes se sont mieux classées en termes de prises moyennes sur 10 ans (tableau 2), alors que les valeurs variaient de 4 530 t par année pour l'option sans limite de taille (PG17 **SLT***) à 3 710 t par année pour les mesures de gestion dont le plafond est supérieur de 150 % à la moyenne, l'allocation récente du plafond aux diverses flottilles (c.-à-d. l'attribution de 59 % au chalut) et l'amortissement sur cinq ans (PG14 **cap1.5_rctAl_am5**). Cette différence était attribuable à deux éléments. Tout d'abord, on a adopté comme principale hypothèse que l'activité de pêche cessait une fois que le TAC était atteint, de sorte que la pêche sans limite de taille réduisait la mortalité des poissons de taille inférieure pour l'ensemble des flottilles. Cette hypothèse a mené à une forte réduction de la croissance de la surpêche pour la procédure de gestion sans limite de taille -  les gains relatifs à la croissance de la taille de la morue charbonnière ont été beaucoup plus élevés que les pertes occasionnées par la mortalité naturelle dans les classes de taille inférieure à la taille réglementaire -  et, par conséquent, à un poids moyen des prises de taille réglementaire plus élevé. Deuxièmement, il a été tenu pour acquis que la pêche pourrait s'effectuer à des taux de mortalité plus élevés parce que la survie par rapport aux classes de taille inférieure était plus grande et qu'il y avait donc un plus grand recrutement pour les pêches et le stock reproducteur. En effet, la cible maximale actuelle $F=5,5\%$/année apparemment conservatrice des procédures de gestion était en grande partie attribuable à la baisse de la survie dans les classes de taille inférieure à la taille réglementaire, ce qui a empêché les procédures de gestion d'atteindre l'objectif 3 de la pêche sur la biomasse du stock reproducteur. En revanche, la procédure de gestion sans limite de taille a presque atteint l'objectif de pêche 3 malgré une cible maximale de $F=7,5 \%$/année pour les poissons de taille réglementaire (tableau 2 - $F_{2021}$).

Les écarts quant aux prises annuelles moyennes étaient plus faibles lorsque les mesures de gestion en mer comportaient une limite de taille. Un plafond de 0 % pour les remises à l'eau et une période d'amortissement de cinq ans (PG6) ont donné des prises d'environ 400 t de plus que la procédure de gestion actuelle (PG15; tableau 2), alors que le gain était de 300 t pour une période d'amortissement de 10 ans (PG5).

Un plafond des remises à l'eau de 50 % de la moyenne historique a entraîné des prises annuelles moyennes de 160 t et 300 t de plus que la procédure de gestion actuelle, selon l'allocation et la période d'amortissement (PG3 et PG4 par rapport à PG15; tableau 2). Fait intéressant, un amortissement sur 10 ans avec un plafond de 0 % produit une prise moyenne sur 10 ans identique à celle fournie par un plafond de 50 % avec une allocation historique et une période d'amortissement de 5 ans (PG5 par rapport à PG6; tableau 2).

Un plafond de remises à l'eau qui équivaut à 100 % de la moyenne historique produit également 200 tonnes de prises annuelles moyennes de plus que la procédure de gestion (PG) actuelle, dans la mesure où le plafond a été attribué en fonction des parts historiques de remises à l'eau et amorti sur cinq ans (PG8 par rapport à PG15, tableau 2). La similitude avec le scénario fixant le plafond à 50 % décrit ci-dessus reflète principalement la part du plafond attribuée à la flottille de chalutiers, où l'allocation récente (59 %) correspond à près du double de l'allocation historique (33 %). Par conséquent, en passant à l'allocation inférieure, l'allocation historique a permis de doubler le plafond (c.-à-d. que les montants totaux des remises à l'eau attribués à la flottille de chalutiers étaient semblables). En général, les options d'allocation historique se sont classées plus haut que les allocations récentes parce que l'allocation historique comprend des remises à l'eau plus faibles par la flottille de chalutiers. La période d'amortissement n'a pas eu un effet aussi notable que les options générales de plafonnement et d'allocation, dans cet ordre.

Le relèvement du plafond à 150 % de la moyenne historique a produit la moyenne annuelle de prises la plus faible, même si la procédure de gestion actuelle n'a aucun plafond (PG13 par rapport à PG15; tableau 2). Bien que les prises moyennes sur 10 ans aient été semblables, les remises à l'eau en vertu de la procédure de gestion actuelle (**sans plafond**) varient principalement selon le recrutement. Elles ont donc moins d'effet qu'un plafond de 150 %, qui a dissocié les remises à l'eau et le recrutement dans une faible mesure. Il a aussi permis à la pêche au chalut de continuer d'excéder les taux actuels de prises de taille inférieure à la taille réglementaire.

À mesure que les plafonds étaient relevés en vertu de la récente allocation de remises à l'eau, la meilleure option en matière d'amortissement est passée d'une période de 5 ans (avec des plafonds bas) à 10 ans (avec des plafonds élevés). Bien que les écarts aient été faibles (PG12 par rapport à PG3; tableau 2), cette transition est probablement attribuable au fait qu'il y a peu d'avantages, voire aucun, sur le plan de la surpêche découlant d'un amortissement avec des plafonds élevés et des allocations récentes. Pour la pêche au chalut, cela signifierait des remises à l'eau plus élevées qu'à l'heure actuelle. Dans le cas qui nous occupe, la période d'amortissement a eu un effet direct sur les TAC, alors que les périodes d'amortissement plus longues ont eu moins d'effet parce que les excédents étalés sur une période plus longue jouent moins sur les rajustements annuels des TAC.

Au départ, il semblait qu'une option sans limite de taille ou des mesures de gestion avec un plafond inférieur auraient une incidence négative sur les recettes de la pêche, parce que les prises débarquées comprendraient des proportions plus élevées de poissons de taille inférieure à la taille réglementaire. La bonification des prix pour la morue charbonnière (tableau 3; C. Acheson, communication personnelle, printemps 2019) peut entraîner un écart de plusieurs dollars la livre entre la morue charbonnière de taille inférieure (< 3 lb) et celle de taille réglementaire (4-5+).

En effet, le revenu moyen par tonne était d'environ 170 $ inférieur pour une pêche au casier sans limite de taille par rapport à la pêche sans plafond (tableau 4), tandis que les recettes étaient d'environ 20 $ et 1 070 $ de moins la tonne pour les prises débarquées par les flottilles de pêche à la palangre et au chalut, respectivement. Les pêches au casier, et surtout les pêches à la palangre, ont opté pour une sélectivité selon la taille se rapprochant suffisamment des plus grandes tailles pour que la conservation des petits poissons ait des conséquences relativement faibles comparativement aux avantages de TAC moyens plus élevés. Les recettes cumulatives sur dix ans ont été de 47 millions de dollars, de 18 millions de dollars et de 15 millions de dollars de plus pour la pêche au casier, à la palangre et au chalut en vertu de la procédure de gestion sans limite de taille, comparativement à la meilleure option suivante du point de vue de la moyenne des prises annuelles (p. ex. PG6, **cap0_am5**; tableau 4).

Les meilleures mesures de gestion des remises à l'eau du point de vue du total des prises et des recettes cumulatives, après l'option sans limite de taille, n'étaient pas les mêmes pour la pêche au casier, à la palangre et au chalut. Par exemple, comme il a été mentionné ci-dessus, la PG6 (**cap0_am5**) était la deuxième meilleure option pour les pêches au casier et à la palangre, en termes de TAC annuel moyen et de recettes cumulatives (tableau 4). En revanche, la deuxième meilleure option pour les recettes de la pêche au chalut était la PG14 (**cap1.5_rctAl_am5**), qui avait le TAC annuel moyen le plus bas. La différence au chapitre des recettes pour les pêches au chalut entre cette option et celle sans limite de taille n'était que de 5 millions de dollars sur 10 ans, tandis que l'écart de recettes entre les PG6 et PG17 pour les pêches au casier et à la palangre était de 33 millions de dollars et de 32 millions de dollars, respectivement. Ainsi, les résultats laissent entendre que les pêches au casier et à la palangre bénéficieraient de mesures de gestion en mer plus restrictives, tandis que la pêche au chalut bénéficierait de mesures de gestion en mer moins restrictives que le statu quo, même sans tenir compte des répercussions sur les principales pêches visées par les pêches au chalut.


#### Modèles d'exploitation de robustesse établis en fonction de l'ajustement $F_{2021}$

Contrairement aux modèles d'exploitation de référence, où les augmentations de la biomasse et des prises sur 10 ans étaient considérables, les estimations concernant la biomasse et les prises de morue charbonnière en vertu des modèles d'exploitation de robustesse ont augmenté plus graduellement, et ont exigé en général des taux de pêche plus faibles pour respecter les objectifs de pêche 1 à 3 (figures 6 et 7). En fait, ces simulations produisent des résultats assez semblables à ceux de l'évaluation précédente des stratégies de gestion de la morue charbonnière, ce qui laisse croire que des stratégies de récolte assez conservatrices s'imposent à long terme pour atteindre les objectifs de pêche 1 à 3 [@cox2019evaluating].

Il a été plus difficile de modifier la procédure de gestion afin qu'elle atteigne l'objectif de pêche 3 en vertu des modèles d'exploitation de robustesse, parce que les valeurs $F$ plus élevées avaient des répercussions plus notables sur l'objectif de déclin à court terme [P(déclin); tableau 5]. L'ajustement de la procédure de gestion a entraîné des taux de mortalité des poissons assez faibles, qui variaient de 5,2 % (procédure de gestion actuelle) à 7,2 % (plafond 0). Ces faibles $F$ ont également eu pour effet d'accroître la probabilité de prises inférieures à 1 992 t (objectif de pêche 4). Même s'ils étaient négligeables (< 3 %) dans les modèles d'exploitation de référence, ils excédaient tous 15 % dans les modèles d'exploitation de robustesse, sauf pour la procédure de gestion sans limite de taille où ils s'établissaient à 8 % (tableau 5).

La moyenne des prises annuelles selon les modèles d'exploitation de robustesse variait de 2 305 t selon la procédure de gestion actuelle (PG15, sans plafond) à 2 767 t selon celle sans limite de taille (PG17, sans limite de taille). Par conséquent, la procédure de gestion actuelle, sans limite des remises à l'eau, a affiché un rendement inférieur à celui de n'importe laquelle des options ayant un plafond, et a même produit 200 t de moins par année pour les options avec plafond les mieux classées (tableau 5). Il y avait une légère différence dans l'ordre de classement des procédures de gestion (classées selon la moyenne des prises sur 10 ans) aux termes des modèles d'exploitation de robustesse, comparativement aux modèles d'exploitation de référence, bien que la différence absolue entre la plupart des procédures de gestion soit faible.

La variation annuelle moyenne des prises se situait entre 9 et 11 % aux fins des modèles d'exploitation de robustesse, comparativement à celle des modèles d'exploitation de référence qui s'établissait entre 7 et 8 % (tableau 5). Cette situation est probablement attribuable au fait que le stock demeure en dessous de $B_{RMS}$ pour la majeure partie de la période de prévision et qu'il est donc parfois évalué en dessous de $B_{RMS}$. Les changements de l'état des stocks et du taux maximal de mortalité cible dans l'évaluation ont été relativement courants dans les versions des procédures de gestion de la morue charbonnière au cours des dernières années, causant un écart interannuel du TAC plus grand.

Les recettes cumulatives sur 10 ans dans le cadre des modèles d'exploitation de robustesse correspondaient à environ 60 % des recettes associées aux modèles d'exploitation de référence (tableau 6). Bien que les échelles absolues diffèrent, les tendances relatives aux valeurs cumulatives étaient semblables à celles des modèles d'exploitation de référence. Ainsi, l'option sans limite de taille a fourni la valeur globale la plus élevée, ainsi que la valeur la plus élevée pour chaque flottille. La deuxième mesure de gestion des remises à l'eau qui a produit les meilleures recettes cumulatives était l'option la plus restrictive pour la pêche au chalut et l'option un peu moins restrictive pour les pêches au casier et à la palangre (PG6, **cap0_am5**; tableau 6).


#### Tests croisés des modèles d'exploitation établis en fonction d'un ajustement $F_{2021}$ inverse

Comme on s'y attendait, il y avait une asymétrie considérable du risque entre les procédures de gestion ajustées en vertu des modèles d'exploitation de robustesse et les modèles d'exploitation de référence. Par exemple, lorsque les procédures de gestion ont été ajustées pour respecter les critères des objectifs de pêche 1 à 3 aux termes des modèles d'exploitation de référence, mais que la classe de 2015 ne s'est pas matérialisée comme ce fut le cas pour les modèles d'exploitation de robustesse, presque toutes les procédures de gestion n'ont pas réussi à respecter les critères de rendement des objectifs de pêche 2 et 3 (tableau 7). L'avantage d'accepter ce risque en matière de conservation était d'environ 150 t de prises annuelles supplémentaires, soit tout au plus une augmentation de 6 % de la moyenne des prises annuelles. 

Par contre, lorsque les procédures de gestion ont été ajustées afin de respecter les critères des objectifs de pêche 1 à 3 dans le cadre des modèles d'exploitation de robustesse et que la classe de 2015 s'est matérialisée comme prévu dans les modèles d'exploitation de référence, toutes les procédures de gestion ont alors respecté les objectifs de pêche 1 à 3 (tableau 8). Cette stratégie plus réfractaire au risque (du point de vue biologique) s'accompagne d'une baisse de la moyenne des prises annuelles d'environ 300 t pour toutes les procédures de gestion, soit de 6,5 à 8 % des prises rajustées en fonction des modèles d'exploitation de référence.
