# Conclusions

La procédure de gestion (PG) actuelle pour la morue charbonnière canadienne (PG15, **sans plafond**), qui ne comporte aucune limite des remises à l'eau, a permis d'atteindre les objectifs biologiques (c.-à-d. les objectifs de pêche 1 à 3) en vertu des modèles d'exploitation de référence et de robustesse. Toutefois, elle s'est classée presque au dernier rang pour ce qui est du rendement des prises, comparativement aux procédures de gestion comptant des mesures de gestion des remises à l'eau. En ce qui concerne les procédures de gestion prévoyant la gestion des remises à l'eau, la PG14 (sans limite de taille), la PG17 (plafond de 0 %, amortissement sur 5 ans) et la PG3 (plafond de 50 %, allocation historique et amortissement sur 5 ans) se sont classées le plus souvent parmi les trois meilleures, tant au chapitre des modèles d'exploitation de référence que de ceux de robustesse, dans la mesure où les taux maximaux de mortalité cibles avaient été rajustés en fonction des trois objectifs de pêche.

Comme l'évaluation des stratégies de gestion précédente l'a indiqué, les procédures de gestion sans limite de taille produisent une moyenne annuelle des prises débarquées plus élevée, tout en permettant à la pêche d'atteindre les objectifs biologiques à court et à long terme. En fait, l'évitement à 100 % serait supérieur à la procédure de gestion sans limite de taille, mais nous n'en avons pas tenu compte ici [@cox2019evaluating]. La procédure de gestion sans limite de taille produit également la plus grande valeur au titre des prises débarquées, ce qui laisse entendre que la bonification des prix accordant une valeur relativement basse à la morue charbonnière de taille inférieure à la taille réglementaire n'a pas beaucoup d'effet sur 10 ans. Ces résultats valent autant pour les modèles d'exploitation de référence que les modèles d'exploitation de robustesse; cependant, il convient de noter que nous n'avons pas inclus les coûts variables de la pêche dans notre analyse. Nous n'avons pas non plus tenu compte des conséquences de ces procédures de gestion sur les pêches qui ciblent d'autres espèces dans le cadre d'une pêche intégrée de poissons de fond en Colombie-Britannique.

La procédure de gestion sans limite de taille a fourni en moyenne un excédent annuel des prises débarquées, tant pour les modèles d'exploitation de référence que les modèles d'exploitation de robustesse, de 500 t et 310 t, respectivement, par rapport à la deuxième procédure de gestion affichant le meilleur rendement. Compte tenu de la structure actuelle des prix en fonction de la taille de la morue charbonnière, ces différences équivalent en moyenne à une valeur totale annuelle des prises débarquées d'environ 8,5 millions de dollars aux termes des modèles d'exploitation de référence et à 5,3 millions de dollars pour les modèles d'exploitation de robustesse.

Quant aux procédures de gestion comportant une limite de taille, l'écart relatif à la moyenne annuelle des prises varie entre les diverses procédures de gestion de 410 t et 200 t, pour les modèles d'exploitation de référence et de robustesse, respectivement. Ces écarts équivalent sur le plan de la valeur moyenne annuelle des prises débarquées totales à environ 7,7 millions de dollars pour les modèles d'exploitation de référence et à 3,6 millions de dollars pour les modèles d'exploitation de robustesse.

Le plus grand risque lié à la conservation semble être l'ajustement d'une procédure de gestion en vue d'atteindre les objectifs de conservation dans le cadre du modèle d'exploitation de référence, seulement pour découvrir par la suite que la classe de 2015 a été surestimée ou ne s'est pas matérialisée comme on l'avait espéré (ce qui ne serait pas sans précédent dans l'industrie de la pêche). Nous avons vérifié les répercussions d'un tel scénario en simulant un test croisé du rendement des procédures de gestion en vertu des modèles d'exploitation de robustesse, où le taux maximal de mortalité cible était ajusté pour les modèles d'exploitation de référence. Comme prévu, le rendement par rapport aux objectifs de pêche 2 et 3 était médiocre pour toutes les procédures de gestion testées.

D'autre part, le test croisé inverse - les procédures de gestion ajustées des modèles d'exploitation de robustesse par rapport aux modèles d'exploitation de référence - a révélé que les procédures de gestion ajustées des modèles d'exploitation de robustesse obtiennent de très bons résultats par rapport aux objectifs de pêche 1 à 3 dans le cadre des modèles d'exploitation de référence. Par conséquent, la perte de rendement associée à l'adoption d'une procédure de gestion ajustée d'un modèle d'exploitation de robustesse est relativement faible, compte tenu du degré élevé de certitude qui s'ajoute sur le plan du rendement en matière de conservation. Ces rendements annuels sont encore beaucoup plus élevés que ceux des dernières années.

Il serait possible de modifier la stratégie pour le prochain cycle d'évaluation des stratégies de gestion (2020-2022), alors que la taille des classes de 2015 pourrait être mieux estimée à mesure que s'ajoutent des années de pêche et des données provenant des relevés.
